################################################################
## Packages / Switch / Scentsy
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'switch/scentsy'

    group.scentsy:
      <<: *customize
      friendly_name: Scentsy Controls

    switch.scentsy:
      <<: *customize
      friendly_name: Scentsy

    automation.scentsy_off_not_home:
      <<: *customize
      friendly_name: Scentsy off not home

    automation.scentsy_on_with_modeling_desk:
      <<: *customize
      friendly_name: Scentsy on with modeling desk

    automation.scentsy_off_with_modeling_desk:
      <<: *customize
      friendly_name: Scentsy off with modeling desk

##################################################
## Switch
##################################################
switch:
  - platform: mqtt
    name: scentsy
    state_topic: "home/sonoff_5/stat/POWER"
    command_topic: "home/sonoff_5/cmnd/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true

##################################################
## Input Number
##################################################
input_number:
  scentsy_time:
    name: Scentsy On Time
    initial: 30
    min: 0
    max: 60
    step: 1

##################################################
## Group
##################################################
group:
  scentsy:
    control: hidden
    entities:
      - switch.scentsy
      - input_number.scentsy_time

##################################################
## Automation
##################################################
automation:
  - alias: scentsy_off_not_home
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.chris_phone
        to: 'not_home'
        for:
          minutes: 5
    action:
      - service: script.notify_discord
        data_template:
          message: 'Turning off scentsy'
      - service: switch.turn_off
        data:
          entity_id:
            - switch.scentsy

  - alias: scentsy_on_with_modeling_desk
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.model
        to: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.scentsy

  - alias: scentsy_off_with_modeling_desk
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.model
        to: 'off'
        for:
          minutes: 30
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.scentsy