################################################################
## Packages / Views / Automation
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'views/automation'

    group.automation:
      <<: *customize
      friendly_name: "Automation"
      icon: mdi:settings

################################################
## Group
################################################
group:
  automation:
    view: yes
    entities:
      - group.all_automations
      - group.all_scripts
      - group.all_scenes