################################################################
## Packages / Views / Default
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'views/default'

    group.default_view:
      <<: *customize
      friendly_name: "Home"
      icon: mdi:home

################################################
## Group
################################################
group:
  default_view:
    view: yes
    entities:
      - group.house_mode
      - group.household_members
      - group.guests
      - group.mail_packages