################################################################
## Packages / Views / Media
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'views/media'

    group.media:
      <<: *customize
      friendly_name: "Media"
      icon: mdi:play-circle-outline

################################################
## Group
################################################
group:
  media:
    view: yes
    entities:
      - group.media_components
      - group.media_players