################################################################
## Packages / Views / Misc
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'views/misc'

    group.misc:
      <<: *customize
      friendly_name: "Misc."
      icon: mdi:puzzle

################################################
## Group
################################################
group:
  misc:
    view: yes
    entities:
      - group.iss
      - group.bitcoin_general
      - group.haveibeenpwned
      - group.aircraft_overhead