homeassistant:
  name: !secret ha_name
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: !secret ha_timezone
  packages: !include_dir_named packages

## INCLUDE ##
conversation:
discovery:
#python_script:
alexa:
config:
updater:
  include_used_components: true

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml