homeassistant:
  name: !secret ha_name
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: !secret ha_timezone
  customize: !include customize.yaml
  packages: !include_dir_named packages

## INCLUDE ##
config:
conversation:

# MQTT Configuration
mqtt: !include mqtt.yaml

# Sun component
sun:

# USPS Component
usps:
  username: !secret usps_username
  password: !secret usps_password

# Devices #
media_player: !include_dir_list devices/media_players/

# Sensors #
sensor: !include_dir_list sensors/

# Device trackers #
device_tracker: !include_dir_list device_trackers/

# Notifiers #
notify: !include_dir_list notifiers/

# Zones #
zone: !include_dir_list zones/

# Cameras #
camera: !include_dir_list cameras/

# Web links #
weblink: !include web_links.yaml

# Front End #
frontend: !include front_end.yaml

# Http #
http:
  api_password: !secret http_pass

# Updater #
updater:
  include_used_components: true

# TTS #
tts:
  - platform: google

discovery:


## LOAD AUTOMATIONS ##
automation: !include_dir_merge_list automations/

## LOAD GROUPS ##
group: !include_dir_merge_named groups/

## LOAD SCRIPTS ##
script: !include scripts.yaml

## ACTIVATE ##
alexa:
history:
logbook: