homeassistant:
  name: !secret ha_name
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: !secret ha_timezone
  packages: !include_dir_named packages

## INCLUDE ##
config:
conversation:
#discovery:
history:
#python_script:
frontend:

# Updater #
updater:
  include_used_components: true

# TTS #
tts:
  - platform: google

## LOAD AUTOMATIONS ##
automation: !include_dir_merge_list automations/

## LOAD SCRIPTS ##
script: !include scripts.yaml

## ACTIVATE ##
alexa:

logbook: