homeassistant:
  name: !secret ha_name
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: !secret ha_timezone
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant

lovelace:
  mode: yaml
discovery:
dialogflow:
history:
logbook:
config:
map:
auth:
updater:
  include_used_components: true

zone:
  - name: Home
    latitude: !secret zone_home_lat
    longitude: !secret zone_home_long
    radius: 200

custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
