homeassistant:
  name: !secret ha_name
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: !secret ha_timezone
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant

lovelace:
  mode: yaml
## INCLUDE ##
discovery:
dialogflow:
history:
logbook:
config:
map:
auth:
updater:
  include_used_components: true
