################################################################
## Packages / HTTP
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'http'

      expose: &expose
        <<: *customize
        haaska_hidden: false

################################################
## HTTP
################################################
http:
  api_password: !secret http_pass
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3
  ssl_certificate: C:\Users\Moose\AppData\Roaming\.homeassistant\secrets\domain-crt.crt
  ssl_key: C:\Users\Moose\AppData\Roaming\.homeassistant\secrets\domain-key.key
  server_port: 443