################################################################
## Packages / Scripts / Arriving Home
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "scripts/arriving_home"

    script.people_arriving_home:
      <<: *customize
      friendly_name: Arriving Home

##################################################
## Script
##################################################
script:
  people_arriving_home:
    sequence:
      # Begin by turning on exterior lights
      - service: script.outside_lights_on

      # Next interior lights
      - service: light.turn_on
        data:
          entity_id: light.scentsy

      # do notifications
      - service: script.notify_discord
        data_template:
          message: >-
            {{ person }} has returned home.
      - service: script.notify_html5
        data_template:
          message: >-
            {{ person }} has returned home.
      - service: script.notify_voice
        data_template:
          cache: true
          message: >-
            {{ person }} has arrived home.
