################################################################
## Packages / Scripts / Bedtime
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'scripts/bedtime'

    script.downstairs_bedtime:
      <<: *customize
      friendly_name: Downstairs Bedtime

##################################################
## Script
##################################################
script:
  downstairs_bedtime:
    sequence:
      - service: media_player.turn_off
        data:
          entity_id: media_player.lg_tv_living_room
      - service: light.turn_off
        data:
          entity_id: light.living_room
      - service: light.turn_off
        data:
          entity_id: light.outside