################################################################
## Packages / Scripts / Chris Nap
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "scripts/chris_nap"

    script.nap_time:
      <<: *customize
      friendly_name: Nap Time

##################################################
## Script
##################################################
script:
  nap_time:
    sequence:
      # Turn off bedroom lights
      - service: light.turn_off
        data:
          entity_id: light.chris_room

      # Send voice notification to enjoy
      - service: script.notify_voice_chris
        data_template:
          message: "Waking you up in an hour and a half.  Enjoy your nap"

      # Wait 10 seconds before turning off voice notifications to allow previous to play fully
      - delay: 00:00:10
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.voice_enabled_chris

      # TODO: Wait 1.5 hours before triggering wakeup routine
      - delay: 00:01:00

      # Call Chris Wakeup Script
      - service: script.chris_wakeup
        data_template:
          nap: "true"
