################################################################
## Packages / Scripts / Chris Bedtime
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'scripts/chris_bedtime'

      expose: &expose
        <<: *customize
        haaska_hidden: false

    script.chris_bedtime:
      <<: *customize
      friendly_name: Chris Bedtime

##################################################
## Script
##################################################
script:
  chris_bedtime:
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.reading_light
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.chris_bed