################################################################
## Packages / Scripts / Chris Bedtime
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'scripts/chris_bedtime'

    script.chris_bedtime:
      <<: *customize
      friendly_name: Chris Bedtime

##################################################
## Script
##################################################
script:
  chris_bedtime:
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.chris_room
      - service: script.reading_time_off
      - service: media_player.volume_set
        data:
          entity_id: media_player.chris_bedroom_speaker
          volume_level: 0.3
      - service: media_player.play_media
        data:
          entity_id: media_player.chris_bedroom_speaker
          media_content_type: MUSIC
          media_content_id: 'https://millerresidence.site/local/audio/taps.mp3'
      - delay: '00:01:00'
      - service: script.notify_voice
        data_template:
          message: >-
            {%- set work_date = states.calendar.moose51789gmailcom.attributes.start_time.split(' ')[0] -%}
            {%- set work_start = as_timestamp(states.calendar.moose51789gmailcom.attributes.start_time) | timestamp_custom('%I:%M%p') -%}
            {%- if work_date == states.sensor.date.state -%}
              You have a shift starting at {{ work_start }}.
            {%- else -%}
              Enjoy your night off.
            {%- endif -%}
            Good night.

      # must be last step or cuts out any TTS playback
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.chris_bed