################################################################
## Packages / Scripts / Chris Bedtime
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "scripts/chris_bedtime"

    script.chris_bedtime:
      <<: *customize
      friendly_name: Chris Bedtime

##################################################
## Script
##################################################
script:
  chris_bedtime:
    sequence:
      # Pause media player
      - service: media_player.media_pause
        data:
          entity_id: media_player.spotify

      # Turn off bedroom lights
      - service: light.turn_off
        data:
          entity_id:
            - light.chris_room

      # Set speaker volume and play goodnight notification
      - service: script.notify_voice_chris
        data_template:
          message: >-
            {%- set work_date = states.calendar.moose51789gmailcom.attributes.start_time.split(' ')[0] -%}
            {%- set work_start = as_timestamp(states.calendar.moose51789gmailcom.attributes.start_time) | timestamp_custom('%I:%M%p') -%}
            {%- if work_date == states.sensor.date.state -%}
              You have a shift starting at {{ work_start }}.
            {%- else -%}
              Enjoy your night off.
            {%- endif -%}
            {{' '}}
            Good night.
      # Turn off voice notifications
      - delay: 00:00:10
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.voice_enabled_chris

      # Lastly, play taps if enabled
      - condition: state
        entity_id: input_boolean.bedtime_music
        state: "on"
      - service: media_player.volume_set
        data:
          entity_id: media_player.chris_bedroom_display
          volume_level: 0.3
      - service: media_player.play_media
        data:
          entity_id: media_player.chris_bedroom_display
          media_content_type: MUSIC
          media_content_id: "https://millerresidence.site/local/audio/taps.mp3"
