################################################################
## Packages / Scripts / Chris Bedtime
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'scripts/chris_bedtime'

    script.chris_wakeup:
      <<: *customize
      friendly_name: Chris Wakeup

##################################################
## Script
##################################################
script:
  chris_wakeup:
    sequence:
      - service: script.notify_discord
        data_template:
          message: Waking Up Chris!
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.chris_bed
      - service: light.turn_on
        data:
          entity_id: light.reading
      - service: light.turn_on
        data:
          entity_id: light.outside
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.chris_bedroom_speaker
          volume_level: '{{states.input_number.alarm_clock_volume}}'
      - service: media_player.play_media
        data:
          entity_id: media_player.chris_bedroom_speaker
          media_content_type: MUSIC
          media_content_id: 'https://millerresidence.site/local/audio/reveille.mp3'
      - delay: '00:00:26'
      - service: script.notify_voice
        data_template:
          message: >-
            {{ ["Good morning Chris.", "Rise and shine sleepyhead.", "Wake up Chris.", "Morning Chris."] | random }}
            {{-'  '-}}
            {{ ["It's time to get ready for work.", "Start getting ready for work.", "Ready to start the work day?"]|random }}
            {{-'  '-}}
            Weather summary: {{ states.sensor.dark_sky_hourly_summary.state }}  Current Temperature: {{ states.sensor.dark_sky_temperature.state | round(0) }} degrees.
            {{-'  '-}}
            {%- if not is_state('sensor.dark_sky_precip', 'unknown') -%}
            Current precipitation is {{ states.sensor.dark_sky_precip.state }}.
            {{-'  '-}}
            {%- endif -%}
            Winds are currently {{ states.sensor.dark_sky_wind_speed.state | round(0) }} miles per hour and are out of the
            {{-' '-}}
            {%- set wind_direction =  states.sensor.dark_sky_wind_bearing.state | round(0) -%}
            {%- if wind_direction >= 315 or wind_direction < 45-%}
              north
            {%- elif wind_direction >= 45 and wind_direction < 135 -%}
              east
            {%- elif wind_direction >= 135 and wind_direction < 225 -%}
              south
            {%- elif wind_direction >= 225 and wind_direction < 315 -%}
              west
            {%- endif -%}.
            {{-'  '-}}
            {{ ["Have a good night", "Enjoy your work night", "Go earn that money"] | random }}.
      - delay: '00:15:00'
      - service: light.turn_off
        data:
          entity_id: light.reading
      - service: light.turn_off
        data:
          entity_id: light.outside
      