################################################################
## Packages / Scripts / Good Morning
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'scripts/goodmorning'

    script.good_morning:
      <<: *customize
      friendly_name: Downstairs Good Morning

##################################################
## Scripts
##################################################
script:
  good_morning:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.tree_light