################################################################
## Packages / Scripts / Good Morning
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "scripts/good_morning"

    script.good_morning:
      <<: *customize
      friendly_name: Downstairs Good Morning

##################################################
## Scripts
##################################################
script:
  good_morning:
    sequence:
      - service: notify.discord
        data:
          message: "Morning wakeup initiated."
      - service: light.turn_on
        data:
          entity_id: light.scentsy
      - service: light.turn_on
        data:
          entity_id: light.outside
