################################################################
## Packages / Scripts / Movie Time
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "scripts/movie_time"

    script.movie_time:
      <<: *customize
      friendly_name: Movie Time

##################################################
## Script
##################################################
script:
  movie_time:
    sequence:
      - service: script.notify_voice_chris
        data:
          message: "Enjoy the movie."
      - delay: 00:00:10
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.voice_enabled_chris
      - service: light.turn_off
        data:
          entity_id: light.overhead
      - service: light.turn_on
        data:
          entity_id: light.reading
      - delay: 02:00:00
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.voice_enabled_chris
