################################################################
## Packages / Groups / Rooms / Blue Room
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms/blue_room'

    group.blue_room_view:
      <<: *customize
      friendly_name: Blue Room

    group.blue_room_lights:
      <<: *customize
      friendly_name: Lights

    group.blue_room_switches:
      <<: *customize
      friendly_name: Switches

    group.blue_room_media_players:
      <<: *customize
      friendly_name: Media Players

##################################################
## Group
##################################################
group:
  blue_room_view:
    view: yes
    entities:
      - group.blue_room_lights
      - group.scentsy

  blue_room_lights:
    control: hidden
    entities:
      - light.blue_room
      - light.model
      - light.overhead_2
  
  blue_room_media_players:
    control: hidden
    entities:
      - media_player.spotify