################################################################
## Packages / Groups / Rooms / Chris Bedroom
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms/chris_bedroom'

      expose: &expose
        <<: *customize
        haaska_hidden: false
    
    group.chris_bedroom_view:
      <<: *customize
      friendly_name: "Chris's Bedroom"

    group.morning_alarm:
      <<: *customize
      friendly_name: Morning Alarm

    group.chris_bedroom_lights:
      <<: *customize
      friendly_name: Lights

    group.chris_bedroom_media_players:
      <<: *customize
      friendly_name: Media Players

##################################################
## Group
##################################################
group:
  chris_bedroom_view:
    view: yes
    entities:
      - group.alarm_clock
      - group.chris_bedroom_lights
      - group.chris_bedroom_media_players
      - group.reading_time
      - group.environment

  chris_bedroom_lights:
    control: hidden
    entities:
      - light.reading_light

  chris_bedroom_media_players:
    control: hidden
    entities:
      - media_player.samsung_tv_chris_bedroom
      - media_player.spotify
      - media_player.gpm_desktop_player