################################################################
## Packages / Groups / Rooms / Chris Bedroom
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms/chris_bedroom'

    group.chris_bedroom_view:
      <<: *customize
      friendly_name: "Chris's Bedroom"

    group.chris_bedroom_lights:
      <<: *customize
      friendly_name: Lights

    group.chris_bedroom_media_players:
      <<: *customize
      friendly_name: Media Players

##################################################
## Group
##################################################
group:
  chris_bedroom_view:
    view: yes
    entities:
      - group.work_day
      - group.chris_bedroom_lights
      - group.chris_bedroom_media_players
      - group.reading_time
      - group.environment
      - group.chris_bed

  chris_bedroom_lights:
    control: hidden
    entities:
      - light.chris_bedroom
      - light.reading
      - light.overhead_2

  chris_bedroom_media_players:
    control: hidden
    entities:
      - media_player.samsung_tv_chris_bedroom
      - media_player.spotify
      - media_player.gpm_desktop_player
      - media_player.chris_bedroom_speaker