################################################################
## Packages / Groups / Rooms / Living Room
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms/living_room'

    group.living_room_view:
      <<: *customize
      friendly_name: Living Room

    group.living_room_lights:
      <<: *customize
      friendly_name: Lights

    group.living_room_media_players:
      <<: *customize
      friendly_name: Media Players

##################################################
## Group
##################################################
group:
  living_room_view:
    view: yes
    entities:
      - group.living_room_lights
      - group.living_room_media_players

  living_room_lights:
    control: hidden
    entities:
      - light.tree_light
      - light.floorlamp_light

  living_room_media_players:
    control: hidden
    entities:
      - media_player.lg_tv_living_room