################################################################
## Packages / Groups / Rooms / Outside
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms/outside'

      expose: &expose
        <<: *customize
        haaska_hidden: false

    group.outside_view:
      <<: *customize
      friendly_name: Outside

    group.outside_lights:
      <<: *customize
      friendly_name: Lights



##################################################
## Group
##################################################
group:
  outside_view:
    view: yes
    entities:
      - group.outside_lights

  outside_lights:
    control: hidden
    entities:
      - light.outside
