################################################################
## Packages / Groups / Automation Override
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/automation_override'

    group.all_automations:
      <<: *customize
      hidden: false
      control: hidden

##################################################
## Automation
##################################################