################################################################
## Packages / Groups / Automation Override
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/automation_override'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.automations_chris:
      <<: *customize
      friendly_name: "Automations Chris"

    group.all_automations:
      <<: *customize
      hidden: false
      control: hidden

################################################
## Group
################################################

group:
  automations_chris:
    entities:
      - automation.alarm_clock
      - automation.reading_light_off_sunrise
