################################################################
## Packages / Groups / Mail
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/mail'

    group.mail_packages:
      <<: *customize
      friendly_name: "Mail / Packages"
      order: 5

################################################
## Group
################################################
group:
  mail_packages:
    control: hidden
    entities:
      - sensor.fedex
      - sensor.ups
      - sensor.usps_mail
      - sensor.usps_packages
      - camera.usps_mail