################################################################
## Packages / Groups / People
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/people'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Device Tracker
    ################################################

    device_tracker.bruce_phone:
      <<: *customize
      friendly_name: "Bruce (Android)"
      icon: mdi:cellphone-android

    device_tracker.chris_miller_phone:
      <<: *customize
      friendly_name: "Chris (Android)"
      icon: mdi:cellphone-android

    device_tracker.cassie_iphone:
      <<: *customize
      friendly_name: "Cassie (iPhone)"
      icon: mdi:cellphone-iphone

    device_tracker.teresa_dills_phone:
      <<: *customize
      friendly_name: "Teresa (iPhone)"
      icon: mdi:cellphone-iphone

    device_tracker.mikayla_phone:
      <<: *customize
      friendly_name: "MiKayla (Android)"
    
    device_tracker.corey_phone:
      <<: *customize
      friendly_name: "Corey (Android)"

    device_tracker.kennady_phone:
      <<: *customize
      friendly_name: "Kennady (Android)"

    ################################################
    ## Group
    ################################################

    group.guests:
      <<: *customize
      friendly_name: "Guests"
      icon: mdi:human-male-female
      order: 1

    group.guests_source:
      <<: *customize
      friendly_name: "Guests"
      hidden: true
    
    group.people:
      <<: *customize
      friendly_name: "Household"
      icon: mdi:human-male-female
      order: 0

    group.people_source:
      <<: *customize
      friendly_name: "Household"
      hidden: true

    group.person_chris:
      <<: *customize
      friendly_name: "Chris"
      icon: mdi:human-male

    group.person_cassie:
      <<: *customize
      friendly_name: "Cassie"
      icon: mdi:human-female
    
    group.person_teresa:
      <<: *customize
      friendly_name: "Teresa"
      icon: mdi:human-female

    group.person_bruce:
      <<: *customize
      friendly_name: "Bruce"
      icon: mdi:human-male

    group.person_mikayla:
      <<: *customize
      friendly_name: "MiKayla"
      icon: mdi:human-female

    group.person_corey:
      <<: *customize
      friendly_name: "Corey"
      icon: mdi:human-male

    group.person_kennady:
      <<: *customize
      friendly_name: "Kennady"
      icon: mdi:human-female

    ################################################
    ## Sensor
    ################################################
    
    sensor.chris_location:
      <<: *customize
      friendly_name: "Chris Location"
      icon: mdi:google-maps
    
    sensor.teresa_location:
      <<: *customize
      friendly_name: "Teresa Location"
      icon: mdi:google-maps

    sensor.bruce_location:
      <<: *customize
      friendly_name: "Bruce Location"
      icon: mdi:google-maps

    sensor.kennady_state:
      <<: *customize
      friendly_name: "Kennady"
      icon: mdi:human-female

    sensor.cassie_state:
      <<: *customize
      friendly_name: "Cassie"
      icon: mdi:human-female

    sensor.mikayla_state:
      <<: *customize
      friendly_name: "MiKayla"
      icon: mdi:human-female

    sensor.corey_state:
      <<: *customize
      friendly_name: "Corey"
      icon: mdi:human-male

    ################################################
    ## Automation
    ################################################

    automation.people_leaving_home:
      <<: *customize
      friendly_name: "People Leaving Home"

    automation.people_returning_home:
      <<: *customize
      friendly_name: "People Returning Home"

################################################
## Group
################################################

group:
  guests:
    control: hidden
    entities:
      - sensor.cassie_state
      - sensor.corey_state
      - sensor.kennady_state
      - sensor.mikayla_state

  guests_source:
    control: hidden
    entities:
      - device_tracker.cassie_iphone
      - device_tracker.corey_phone
      - device_tracker.kennady_phone
      - device_tracker.mikayla_phone

  people:
    control: hidden
    entities:
      - group.person_chris
      - group.person_teresa
      - group.person_bruce

  people_source:
    control: hidden
    entities:
      - device_tracker.chris_miller_phone
      - device_tracker.teresa_dills_phone
      - device_tracker.bruce_phone

  person_bruce:
    control: hidden
    entities:
      - device_tracker.bruce_phone
      - sensor.bruce_location

  person_chris:
    control: hidden
    entities:
      - device_tracker.chris_miller_phone
      - sensor.chris_location

  person_cassie:
    control: hidden
    entities:
      - device_tracker.cassie_iphone
    
  person_corey:
    control: hidden
    entities:
      - device_tracker.corey_phone

  person_kennady:
    control: hidden
    entities:
      - device_tracker.kennady_phone

  person_mikayla:
    control: hidden
    entities:
      - device_tracker.mikayla_phone
  
  person_teresa:
    control: hidden
    entities:
      - device_tracker.teresa_dills_phone
      - sensor.teresa_location

################################################
## Sensor
################################################

sensor:
  - platform: google_geocode
    origin: device_tracker.chris_miller_phone
    options: street, city
    name: chris_location
    api_key: !secret google_api_key

  - platform: google_geocode
    origin: device_tracker.teresa_dills_phone
    options: street, city
    name: teresa_location
    api_key: !secret google_api_key

  - platform: google_geocode
    origin: device_tracker.bruce_phone
    options: street, city
    name: bruce_location
    api_key: !secret google_api_key

  - platform: template
    sensors:
      kennady_state:
        value_template: "{{'Visiting' if is_state('device_tracker.kennady_phone', 'home') else 'Away'}}"
      
      corey_state:
        value_template: "{{'Visiting' if is_state('device_tracker.corey_phone', 'home') else 'Away'}}"
      
      mikayla_state:
        value_template: "{{'Visiting' if is_state('device_tracker.mikayla_phone', 'home') else 'Away'}}"
      
      cassie_state:
        value_template: "{{'Visiting' if is_state('device_tracker.cassie_iphone', 'home') else 'Away'}}"

################################################
## Automations
################################################

automation:
  - alias: people_leaving_home
    trigger:
      - platform: state
        from: 'home'
        to: 'not_home'
        entity_id: group.person_chris, group.person_bruce, group.person_teresa
    action:
      - service: notify.discord
        data_template:
          target: '355096664241078272'
          message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] {{ trigger.to_state.attributes.friendly_name }} has left home.'

  - alias: people_returning_home
    trigger:
      - platform: state
        from: 'not_home'
        to: 'home'
        entity_id: group.person_chris, group.person_bruce, group.person_teresa
    action:
      - service: notify.discord
        data_template:
          target: '355096664241078272'
          message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] {{ trigger.to_state.attributes.friendly_name }} has returned home.'

##################################################
## Intent Scripts
##################################################
intent_script:
  # Give status of household members
  WhereAreWeIntent:
    speech:
      text: >
        {%- if is_state('device_tracker.bruce_phone.household', 'home') and is_state('device_tracker.chris_miller_phone', 'home') and is_state('device_tracker.teresa_dills_phone', 'home') -%}
          Everyone is currently home
        {%- else -%}
          Chris is at {% if is_state('device_tracker.chris_miller_phone', 'home') %}home{% else %}{% if not is_state('states.sensor.chris_location', 'Awaiting Update') %}Unknown Location{% else %}{{ states.sensor.chris_location.attributes['Street'] }}, {{ states.sensor.chris_location.attributes['City'] }}{% endif %}{% endif %}, Teresa is at {% if is_state('device_tracker.teresa_dills_phone', 'home') %}home{% else %}{% if not is_state('states.sensor.teresa_location', 'Awaiting Update') %}Unknown Location{% else %}{{ states.sensor.teresa_location.attributes['Street'] }}, {{ states.sensor.teresa_location.attributes['City'] }}{% endif %}{% endif %}, and Bruce is at {% if is_state('device_tracker.bruce_phone', 'home') %}home{% else %}{% if not is_state('states.sensor.bruce_location', 'Awaiting Update') %}{% if as_timestamp(now())  | timestamp_custom('%H', true) | int >= 15 and as_timestamp(now()) | timestamp_custom('%H', true) | int <= 23 %}work most likely{% else %}unknown location{% endif %}{% else %}{{ states.sensor.bruce_location.attributes['Street'] }}, {{ states.sensor.bruce_location.attributes['City'] }}{% endif %}{% endif %}.
        {% endif %}

  # List off who is currently at home
  WhosHomeIntent:
    speech:
      text: >
        {% if is_state('states.group.people.state', 'home') %}I show everyone as currently home.{% elif is_state('states.group.people.state', 'not_home') %}I show the house as empty, should i be concerned that someone is talking to me?{% else %}I see people.  Specifically{% if is_state('device_tracker.chris_miller_phone', 'home') %}, Chris{%endif %}{% if is_state('device_tracker.teresa_dills_phone', 'home') %}, Teresa{%endif %}{% if is_state('device_tracker.bruce_phone', 'home') %}, Bruce{%endif%}.{% endif %}

  # Guests visiting
  WhosVisitingIntent:
    speech:
      text: >
        {% if is_state('states.group.guests', 'home') %}I'm showing at least one guest.  They are{% if is_state('device_tracker.cassie_iphone', 'home') %}, Cassie{%endif%}{% if is_state('device_tracker.corey_phone', 'home') %}, Corey{%endif%}{% if is_state('device_tracker.kennady_phone', 'home') %}, Kennady Paige{%endif%}{% if is_state('device_tracker.mikayla_phone', 'home') %}, MiKayla{%endif%}{% else %}Currently you have no guests.{% endif %}