################################################################
## Packages / Groups / People
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/people'

    device_tracker.bruce_phone:
      <<: *customize
      friendly_name: "Bruce (Android)"
      icon: mdi:cellphone-android

    device_tracker.chris_phone:
      <<: *customize
      friendly_name: "Chris (Android)"
      icon: mdi:cellphone-android

    device_tracker.teresa_phone:
      <<: *customize
      friendly_name: "Teresa (Android)"
      icon: mdi:cellphone-android

    group.guests:
      <<: *customize
      friendly_name: "Guests"
      icon: mdi:human-male-female
      order: 2

    group.guests_source:
      <<: *customize
      friendly_name: "Guests"
      hidden: true
    
    group.household_members:
      <<: *customize
      friendly_name: "Household"
      icon: mdi:human-male-female
      order: 1

    group.household_members_source:
      <<: *customize
      friendly_name: "Household"
      hidden: true
    
    sensor.kennady_location:
      <<: *customize
      friendly_name: "Kennady"
      icon: mdi:human-female

    sensor.cassie_location:
      <<: *customize
      friendly_name: "Cassie"
      icon: mdi:human-female

    sensor.mikayla_location:
      <<: *customize
      friendly_name: "MiKayla"
      icon: mdi:human-female

    sensor.brandon_location:
      <<: *customize
      friendly_name: "Brandon"
      icon: mdi:human-male

    sensor.erin_location:
      <<: *customize
      friendly_name: "Erin"
      icon: mdi:human-female

    sensor.corey_location:
      <<: *customize
      friendly_name: "Corey"
      icon: mdi:human-male

    sensor.bruce_location:
      <<: *customize
      friendly_name: "Bruce"
      icon: mdi:human-male

    sensor.chris_location:
      <<: *customize
      friendly_name: "Chris"
      icon: mdi:human-male
    
    sensor.teresa_location:
      <<: *customize
      friendly_name: "Teresa"
      icon: mdi:human-female

    automation.guests_visit:
      <<: *customize
      friendly_name: "Guests Visit"
    
    automation.people_leaving_home:
      <<: *customize
      friendly_name: "People Leaving Home"

    automation.people_returning_home:
      <<: *customize
      friendly_name: "People Returning Home"

################################################
## Group
################################################
group:
  guests:
    control: hidden
    entities:
      - sensor.cassie_location
      - sensor.corey_location
      - sensor.kennady_location
      - sensor.mikayla_location
      - sensor.brandon_location
      - sensor.erin_location

  guests_source:
    control: hidden
    entities:
      - device_tracker.cassie_phone
      - device_tracker.corey_phone
      - device_tracker.kennady_phone
      - device_tracker.mikayla_phone
      - device_tracker.brandon_phone
      - device_tracker.erin_phone

  household_members:
    control: hidden
    entities:
      - sensor.chris_location
      - sensor.teresa_location
      - sensor.bruce_location
  
  household_members_source:
    control: hidden
    entities:
      - device_tracker.chris_phone
      - device_tracker.teresa_phone
      - device_tracker.bruce_phone

################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    state_topic: "household/location/chris"
    name: chris_house_location
    value_template: '{{ value_json.location }}'
  
  - platform: mqtt
    state_topic: "household/location/teresa"
    name: teresa_house_location
    value_template: '{{ value_json.location }}'

  - platform: mqtt
    state_topic: "household/location/bruce"
    name: bruce_house_location
    value_template: '{{ value_json.location }}'

  - platform: template
    sensors:
      kennady_location:
        value_template: "{{'Visiting' if is_state('device_tracker.kennady_phone', 'home') else 'Away'}}"
      
      corey_location:
        value_template: "{{'Visiting' if is_state('device_tracker.corey_phone', 'home') else 'Away'}}"
      
      mikayla_location:
        value_template: "{{'Visiting' if is_state('device_tracker.mikayla_phone', 'home') else 'Away'}}"
      
      cassie_location:
        value_template: "{{'Visiting' if is_state('device_tracker.cassie_phone', 'home') else 'Away'}}"

      brandon_location:
        value_template: "{{'Visiting' if is_state('device_tracker.brandon_phone', 'home') else 'Away'}}"
      
      erin_location:
        value_template: "{{'Visiting' if is_state('device_tracker.erin_phone', 'home') else 'Away'}}"

      chris_location:
        value_template: >
          {%- if is_state('device_tracker.chris_phone', 'home') -%}
            {%- if is_state('sensor.chris_house_location', 'unknown') -%}
              Home
            {%- else -%}
              {{ states.sensor.chris_house_location.state | capitalize }}
            {%- endif -%}
          {%- else -%}
            Away
          {%- endif -%}

      teresa_location:
        value_template: >
          {%- if is_state('device_tracker.teresa_phone', 'home') -%}
            {%- if is_state('sensor.teresa_house_location', 'unknown') -%}
              Home
            {%- else -%}
              {{ states.sensor.teresa_house_location.state | capitalize }}
            {%- endif -%}
          {%- else -%}
            Away
          {%- endif -%}

      bruce_location:
        value_template: >
          {%- if is_state('device_tracker.bruce_phone', 'home') -%}
            {%- if is_state('sensor.bruce_house_location', 'unknown') -%}
              Home
            {%- else -%}
              {{ states.sensor.bruce_house_location.state | capitalize }}
            {%- endif -%}
          {%- else -%}
            Away
          {%- endif -%}

################################################
## Automations
################################################
automation:
  - alias: people_leaving_home
    initial_state: true
    trigger:
      - platform: state
        from: 'home'
        to: 'not_home'
        for:
          minutes: 1
        entity_id: device_tracker.chris_phone, device_tracker.teresa_phone, device_tracker.bruce_phone
    action:
      - service: script.notify_discord
        data_template:
          message: >-
            {{ trigger.to_state.attributes.friendly_name.split(' ')[0] }} has left home.
      - service: light.turn_off
        data:
          entity_id: light.outside

  - alias: people_returning_home
    initial_state: true
    trigger:
      - platform: state
        from: 'not_home'
        to: 'home'
        entity_id: device_tracker.chris_phone, device_tracker.teresa_phone, device_tracker.bruce_phone
    action:
      - service: script.people_arriving_home
        data_template:
          person: >-
            {{ trigger.to_state.attributes.friendly_name.split(' ')[0] }}

  - alias: guests_visit
    initial_state: true
    trigger:
      - platform: state
        from: 'not_home'
        to: 'home'
        entity_id: 
          - device_tracker.cassie_phone
          - device_tracker.corey_phone
          - device_tracker.kennady_phone
          - device_tracker.mikayla_phone
          - device_tracker.brandon_phone
          - device_tracker.erin_phone
    action:
      - service: script.notify_html5
        data_template:
          message: >-
            {{ trigger.to_state.attributes.friendly_name.split(' ')[0] }} is visiting
      - service: script.notify_voice
        data_template:
          cache: true
          message: >-
            {{ trigger.to_state.attributes.friendly_name.split(' ')[0] }} is here to visit.