################################################################
## Packages / Groups / Rooms
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/rooms'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.living_room:
      <<: *customize
      friendly_name: "Living Room"

    group.computer_room:
      <<: *customize
      friendly_name: "Computer Room"

    group.chris_bedroom:
      <<: *customize
      friendly_name: "Chris's Bedroom"

################################################
## Group
################################################

group:
  living_room:
    control: hidden
    entities:
      - media_player.lg_tv_living_room

  chris_bedroom:
    control: hidden
    entities:
      - media_player.samsung_tv_chris_bedroom
      - switch.reading_light
      - input_select.alarm_clock
  
  computer_room:
    control: hidden
    entities:
      - sensor.net_printer_computer_room