################################################################
## Packages / Groups / Scenes
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/scenes'

      expose: &expose
        <<: *customize
        haaska_hidden: false

##################################################
## Scene
##################################################