################################################################
## Packages / Groups / Scripts
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/scripts'

    group.all_scripts:
      <<: *customize
      hidden: false
      control: hidden

##################################################
## Scripts
##################################################
