################################################################
## Packages / Groups / Scripts
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'groups/scripts'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    group.all_scripts:
      <<: *customize
      hidden: false
      control: hidden
