################################################################
## Packages / Switch / Computer Room Floor Lamp
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'switch/computer_room_floor_lamp'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    switch.computer_floorlamp:
      <<: *customize
      friendly_name: Floor Lamp
      haaska_name: Computer Light

#################################################
## Switch
#################################################
switch:
  - platform: mqtt
    name: computer_floorlamp
    state_topic: "home/sonoff_3/stat/POWER"
    command_topic: "home/sonoff_3/cmnd/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true