################################################################
## Packages / Switch / Sonoff 1
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'switch/sonoff_1'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    switch.sonoff_1:
      <<: *customize
      friendly_name: Reading Light
      emulated_hue: true
      emulated_hue_name: Reading Light

    automation.reading_light_off_not_home:
      <<: *customize
      friendly_name: Reading Light Off Leaving Home

#################################################
## Switch
#################################################
switch:
  - platform: mqtt
    name: sonoff_1
    state_topic: "home/sonoff_1/stat/POWER"
    command_topic: "home/sonoff_1/cmnd/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true

##################################################
## Automations
##################################################
automation:
  - alias: reading_light_off_not_home
    hide_entity: true
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.chris_phone
        to: 'not_home'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: sensor.xbox_current_activity
        state: 'Offline'
    action:
      - service: script.notify_discord
        data_template:
          message: 'Turning off reading light - chris left home'
      - service: switch.turn_off
        data:
          entity_id:
            - switch.sonoff_1

##################################################
## Intent Scripts
##################################################
intent_script:
  ReadingLightOnIntent:
    speech:
      text: "Ok"
    action:
      service: switch.turn_on
      entity_id: switch.sonoff_1
  ReadingLightOffIntent:
    speech:
      text: "Ok"
    action:
      service: switch.turn_off
      entity_id: switch.sonoff_1