################################################################
## Packages / Scripts / Notify / HTML5
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'scripts/notify/html5'

    script.notify_html5:
      <<: *customize
      friendly_name: Notify All

##################################################
## Notify
##################################################
notify:
  - name: notifications
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

##################################################
## Script
##################################################
script:
  notify_html5:
    sequence:
      - service: notify.notifications
        data_template:
          message: '{{ message }}'
          data:
            tag: '{{ tag }}'