################################################################
## Packages / Light / Computer Room Floor Lamp
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light/computer_room_floor_lamp'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    light.computer_floorlamp:
      <<: *customize
      friendly_name: Floor Lamp
      haaska_name: Computer Light
      google_assistant_name: Computer Light

    automation.computer_light_off:
      <<: *customize
      friendly_name: Computer Light Off

#################################################
## Light
#################################################
light:
  - platform: mqtt
    name: computer_floorlamp
    state_topic: "home/sonoff_3/stat/POWER"
    command_topic: "home/sonoff_3/cmnd/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true

##################################################
## Automations
##################################################
automation:
  - alias: computer_light_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.household
        to: 'away'
        for:
          minutes: 5
    action:
      - service: script.notify_discord
        data_template:
          message: 'Turning off computer light - nobody home'
      - service: light.turn_off
        data:
          entity_id:
            - light.computer_floorlamp