################################################################
## Packages / Light / Living Room Floor
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light/living_room_floor'

    light.living_room_floor:
      <<: *customize
      friendly_name: Floor Light

#################################################
## Light
#################################################
light:
  - platform: mqtt
    name: living_room_floor
    state_topic: "home/sonoff_4/stat/POWER"
    command_topic: "home/sonoff_4/cmnd/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true