################################################################
## Packages / Light / Model Light
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light/model_light'

    light.model:
      <<: *customize
      friendly_name: Model Light

    automation.model_light_off_not_home:
      <<: *customize
      friendly_name: Model Light Off Not Home

#################################################
## Light
#################################################
light:
  - platform: mqtt
    name: model
    state_topic: "home/sonoff_6/stat/POWER"
    command_topic: "home/sonoff_6/cmnd/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true

##################################################
## Automations
##################################################
automation:
  - alias: model_light_off_not_home
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.chris_phone
        to: 'not_home'
        for:
          minutes: 5
    action:
      - service: script.notify_discord
        data_template:
          message: 'Turning off modeling light'
      - service: light.turn_off
        data:
          entity_id:
            - light.modeling