################################################################
## Packages / Light / Porch
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light/porch'

    automation.porch_light_force_off:
      <<: *customize
      friendly_name: "Force Porch Light Off"

#################################################
## Automation
#################################################
automation:
  - alias: porch_light_force_off
    initial_state: true
    trigger:
      - platform: state
        from: 'unavailable'
        entity_id: light.porch
    condition:
      - condition: state
        state: 'above_horizon'
        entity_id: sun.sun
      - condition: state
        state: 'on'
        entity_id: light.porch
    action:
      - service: script.notify_discord
        data_template:
          message: >-
            Forcing off outside light - sun is up
      - service: light.turn_off
        data:
          entity_id: light.porch
