################################################################
## Packages / Light / Reading
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light/reading'

    light.reading:
      <<: *customize
      friendly_name: Reading Light

#################################################
## Light
#################################################
light:
  - platform: mqtt
    name: reading
    state_topic: "home/sonoff_1/stat/POWER1"
    command_topic: "home/sonoff_1/cmnd/POWER"
    availability_topic: "home/sonoff_1/tele/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true