################################################################
## Packages / Light / Reading Light
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light/reading_light'

      expose: &expose
        <<: *customize
        haaska_hidden: false

    light.reading_light:
      <<: *customize
      friendly_name: Reading Light

    automation.reading_light_off_not_home:
      <<: *customize
      friendly_name: Reading Light Off Leaving Home

#################################################
## Light
#################################################
light:
  - platform: mqtt
    name: reading_light
    state_topic: "home/sonoff_1/stat/POWER"
    command_topic: "home/sonoff_1/cmnd/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true

##################################################
## Automations
##################################################
automation:
  - alias: reading_light_off_not_home
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.chris_phone
        to: 'not_home'
        for:
          minutes: 5
    action:
      - service: script.notify_discord
        data_template:
          message: 'Turning off reading light - chris left home'
      - service: light.turn_off
        data:
          entity_id:
            - light.reading_light