################################################################
## Packages / Light / Tree Light
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light/tree_light'

      expose: &expose
        <<: *customize
        haaska_hidden: false

    light.tree_light:
      <<: *customize
      friendly_name: Tree Light

    automation.tree_light_off:
      <<: *customize
      friendly_name: Tree Light Off

    automation.tree_light_on:
      <<: *customize
      friendly_name: Tree Light On

#################################################
## Light
#################################################
light:
  - platform: mqtt
    name: tree_light
    state_topic: "home/sonoff_2/stat/POWER"
    command_topic: "home/sonoff_2/cmnd/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true

##################################################
## Automations
##################################################
automation:
  - alias: tree_light_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.household
        to: 'away'
        for:
          minutes: 5
    action:
      - service: script.notify_discord
        data_template:
          message: 'Turning off tree light'
      - service: light.turn_off
        data:
          entity_id:
            - light.tree_light

  - alias: tree_light_on
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.household
        to: 'home'
    action:
      - service: script.notify_discord
        data_template:
          message: 'Turning on tree light'
      - service: light.turn_on
        data:
          entity_id:
            - ligh.tree_light