################################################################
## Packages / Light / Tree
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'light/tree'

    light.tree:
      <<: *customize
      friendly_name: Tree Light

#################################################
## Light
#################################################
light:
  - platform: mqtt
    name: tree
    state_topic: "home/sonoff_2/stat/POWER1"
    command_topic: "home/sonoff_2/cmnd/POWER"
    availability_topic: "home/sonoff_2/tele/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: true