- alias: 'Device Status'
  hide_entity: True
  trigger:
    - platform: state
      entity_id:
        - sensor.hp_printer
        - sensor.echo_show
        - sensor.echo_dot
        - sensor.teresa_tablet
        - sensor.chris_laptop
        - sensor.samsung_smart_tv
        - sensor.chris_xboxone
        - sensor.playstation_3
        - sensor.bruce_phone
        - sensor.teresa_laptop
        - sensor.living_room_tv
        - sensor.chris_miller_phone
        - sensor.teresa_dills_phone
      to: 'offline'
      for:
        minutes: 5
  action:
    - service: notify.discord
      data_template:
        target: '355096664241078272'
        message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] {{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}'