# Turn off TV if all three devices are gone
- alias: 'Living TV Off leaving home'
  trigger:
    - platform: state
      from: 'home'
      to: 'not_home'
      entity_id: group.phones
  action:
    - service: notify.discord
      data_template:
        target: '355096664241078272'
        message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] Turning off living room TV'
    - service: media_player.turn_off
      entity_id: media_player.lg_smart_tv