# Phones leave
- alias: 'People Leaving Home'
  trigger:
    - platform: state
      from: 'home'
      to: 'not_home'
      entity_id:
        - device_tracker.teresa_dills_phone
        - device_tracker.bruce_phone
        - device_tracker.chris_miller_phone
  condition: []
  action:
    - service: notify.discord
      data_template:
        target: '355096664241078272'
        message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] {{ trigger.to_state.attributes.friendly_name }} has left home.'

# Phones Return
- alias: 'People Returning Home'
  trigger:
    - platform: state
      from: 'not_home'
      to: 'home'
      entity_id:
        - device_tracker.teresa_dills_phone
        - device_tracker.bruce_phone
        - device_tracker.chris_miller_phone
  condition: []
  action:
    - service: notify.discord
      data_template:
        target: '355096664241078272'
        message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] {{ trigger.to_state.attributes.friendly_name }} has returned home.'