# Sunset
- alias: 'Notify Discord at sunset'
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:00:00'
  condition: []
  action:
    - service: notify.discord
      data_template:
        target: '355096664241078272'
        message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] The sun has set and will return tomorrow at {{ as_timestamp(states.sun.sun.attributes.next_dawn) | timestamp_custom("%H:%M%p") }}.'

# Sunrise
- alias: 'Notify Discord at sunrise'
  trigger:
    - platform: sun
      event: sunrise
      offset: '+00:00:00'
  condition: []
  action:
    - service: notify.discord
      data_template:
        target: '355096664241078272'
        message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] Sunrise.  Projected sunset for today is {{ as_timestamp(states.sun.sun.attributes.next_dusk) | timestamp_custom("%H:%M%p") }}.'