################################################################
## Packages / Views / Rooms / Chris Bedroom
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "views/rooms/chris_bedroom"

    group.chris_bedroom_view:
      <<: *customize
      friendly_name: "Chris's Bedroom"

##################################################
## Group
##################################################
group:
  chris_bedroom_view:
    view: yes
    entities:
      - group.work_day
      - group.chris_bedroom_lights
      - group.chris_bedroom_media_players
      - group.reading_time
      - group.environment
      - group.chris_bed
      - group.chris_alarm_clock
