################################################################
## Packages / Views / Rooms / Computer Room
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'views/rooms/computer_room'

    group.computer_room_view:
      <<: *customize
      friendly_name: Computer Room

    group.computer_room_lights:
      <<: *customize
      friendly_name: Lights


##################################################
## Group
##################################################
group:
  computer_room_view:
    view: yes
    entities:
      - group.computer_room_lights

  computer_room_lights:
    control: hidden
    entities:
      - light.computer_room
      - light.computer_room_floor