################################################################
## Packages / Views / Rooms / Model Room
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'views/rooms/model_room'

    group.model_room_view:
      <<: *customize
      friendly_name: Model Room

    group.model_room_lights:
      <<: *customize
      friendly_name: Lights

    group.model_room_switches:
      <<: *customize
      friendly_name: Switches

    group.model_room_media_players:
      <<: *customize
      friendly_name: Media Players

##################################################
## Group
##################################################
group:
  model_room_view:
    view: yes
    entities:
      - group.model_room_lights
      - group.scentsy
      - group.model_room_media_players

  model_room_lights:
    control: hidden
    entities:
      - light.spare_room
      - light.model_room
      - light.model_desk
      - light.overhead_2
  
  model_room_media_players:
    control: hidden
    entities:
      - media_player.spotify