################################################################
## Packages / Views / Rooms / Spare Room
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'views/rooms/spare_room'

    group.spare_room_view:
      <<: *customize
      friendly_name: Spare Room

    group.spare_room_lights:
      <<: *customize
      friendly_name: Lights

##################################################
## Group
##################################################
group:
  spare_room_view:
    view: yes
    entities:
      - group.spare_room_lights

  spare_room_lights:
    control: hidden
    entities:
      - light.spare_room
      - light.overhead_2
