################################################################
## Packages / Switch / Christmas View
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'switch/christmas_view'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    group.christmas_view:
      <<: *customize
      friendly_name: Christmas
      icon: mdi:pine-tree

##################################################
## Group
##################################################
group:
  christmas_view:
    view: yes
    entities:
      - switch.christmas_tree
      - switch.garland_lights