################################################################
## Packages / Switch / Christmas Tree
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'switch/christmas_tree'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    switch.christmas_tree:
      <<: *customize
      friendly_name: Christmas Tree

#################################################
## Switch
#################################################
switch:
  - platform: mqtt
    name: christmas_tree
    state_topic: "home/sonoff_2/stat/POWER"
    command_topic: "home/sonoff_2/cmnd/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true

