################################################################
## Packages / Switch / Garland Lights
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'switch/garland_lights'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    switch.garland_lights:
      <<: *customize
      friendly_name: Garland Lights
      haaska_name: Christmas Garland

#################################################
## Switch
#################################################
switch:
  - platform: mqtt
    name: garland_lights
    state_topic: "home/sonoff_4/stat/POWER"
    command_topic: "home/sonoff_4/cmnd/power"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true