################################################################
## Packages / Air Visual
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'airvisual'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################
    group.airvisual_general:
      <<: *customize
      friendly_name: AirVisual

################################################
## Sensor
################################################
sensor:
  - platform: airvisual
    api_key: !secret air_visual_api_key
    monitored_conditions:
      - us
    radius: 500

################################################
## Group
################################################
group:
  airvisual_general:
    control: hidden
    entities:
      - sensor.us_air_pollution_level
      - sensor.us_air_quality_index
      - sensor.us_main_pollutant