################################################################
## Packages / Alarm Control Panel
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'alrm_control_panel'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    group.alarm_control_panel:
      <<: *customize
      friendly_name: Alarm Control Panel

################################################
## Alarm Control Panel
################################################
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: "home/alarm/"
    command_topic: "home/alarm/set"

##################################################
## Group
##################################################
group:
  alarm_control_panel:
    control: hidden
    entities:
      - alarm_control_panel.ha_alarm