################################################################
## Packages / Alexa
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'google_assistant'

##################################################
## Alexa
##################################################
cloud:
  alexa:
    filter:
      include_domains:
        - alert
        #- automation
        - cover
        - fan
        #- group
        #- input_boolean
        - light
        #- media_player
        - scene
        - script
        - switch
      
      exclude_entities:
        - script.notify_discord
        - script.notify_html5
        - script.notify_voice
        - light.overhead
        - light.overhead_2
        - light.overhead_3
        - light.other

    entity_config:
      media_player.lg_tv_living_room:
        name: TV
      script.downstairs_bedtime:
        name: Bedtime
      script.good_morning:
        name: Good Morning