################################################################
## Packages / Arlo
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "arlo"

##################################################
## Arlo
##################################################
arlo:
  username: !secret arlo_username
  password: !secret arlo_password

##################################################
## Alarm
##################################################
alarm_control_panel:
  - platform: arlo

##################################################
## FFmpeg
##################################################
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

##################################################
## Sensor
##################################################
sensor:
  - platform: arlo
    monitored_conditions:
      - captured_today
      - last_capture
      - total_cameras
      - battery_level
      - signal_strength

##################################################
## Camera
##################################################
camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'