################################################################
## Packages / Battery
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'battery'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    group.batteries:
      <<: *customize
      friendly_name: "Batteries"
      order: 3

    sensor.battery_chris_phone:
      <<: *customize
      friendly_name: "Chris Phone"
      unit_of_measurement: "%"

    sensor.battery_teresa_phone:
      <<: *customize
      friendly_name: "Teresa Phone"
      unit_of_measurement: "%"


##################################################
## Group
##################################################
group:
  batteries:
    control: hidden
    entities:
      - sensor.battery_chris_phone
      - sensor.battery_teresa_phone

##################################################
## Sensor
##################################################
sensor:    
  - platform: template
    sensors:
      battery_chris_phone:
        value_template: '{{ states.device_tracker.chris_phone.attributes.battery }}'
        icon_template: >-
          {% set battery_level = states.device_tracker.chris_phone.attributes.battery | int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      battery_teresa_phone:
        value_template: '{{ states.device_tracker.teresa_phone.attributes.battery }}'
        icon_template: >-
          {% set battery_level = states.device_tracker.teresa_phone.attributes.battery | int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

##################################################
## Automation
##################################################
automation:
  - alias: notify_phone_battery_low
    initial_state: true
    hide_entity: true
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.battery_chris_phone
          - sensor.battery_teresa_phone
        below: 20
    action:
      - service: script.notify_discord
        data_template:
          message: "{{ trigger.to_state.attributes.friendly_name }}'s phone needs to charged."