################################################################
## Packages / Chris Work Day
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "work_day"

    binary_sensor.work_day:
      <<: *customize
      friendly_name: Chris Work Day

    automation.chris_work_day_begin:
      <<: *customize
      friendly_name: Chris Work Day Begin

##################################################
## Binary Sensor
##################################################
binary_sensor:
  - platform: template
    sensors:
      work_day:
        value_template: >-
          {{ states.calendar.moose51789gmailcom.attributes['offset_reached'] }}

##################################################
## Automation
##################################################
automation:
  - alias: chris_work_day_begin
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.work_day
        to: "on"
    action:
      - service: script.chris_wakeup
