################################################################
## Packages / Chris Bedtime
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'chris_bedtime'

      expose: &expose
        <<: *customize
        haaska_hidden: false

    input_boolean.chris_bed:
      <<: *customize
      friendly_name: "Chris Asleep"
      icon: mdi:sleep

    group.chris_bed:
      <<: *customize
      friendly_name: "Sleep"

##################################################
## Group
##################################################
group:
  chris_bed:
    control: hidden
    entities:
      - input_boolean.chris_bed

##################################################
## Input Boolean
##################################################
input_boolean:
  chris_bed: