################################################################
## Packages / Cloud
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "cloud"

##################################################
## Cloud
##################################################
cloud:
  google_actions:
    filter:
      include_domains:
        #- group
        #- input_boolean
        - scene
        - script
        - switch
        - fan
        - light
        - cover
        #- media_player
        - climate
      exclude_entities:
        - light.toy_room
        - light.outside
        - light.spare_room
        - light.model_room
        - light.computer_room
        - light.chris_room
        - light.living_room
        - light.other
        - script.movie_activity_start
        - script.movie_activity_end
        - script.notify_discord
        - script.notify_html5
        - script.notify_voice
        - script.people_arriving_home
        - script.outside_lights_on
        - switch.cable_modem
      include_entities:
        - input_boolean.voice_enabled
        - input_boolean.voice_enabled_chris
        - input_boolean.reading_time
    entity_config:
      script.chris_wakeup:
        name: Chris Wake Up
      script.chris_bedtime:
        name: Chris Bedtime
      script.downstairs_bedtime:
        name: Downstairs Bedtime
