################################################################
## Packages / Crime Reports
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'crime_reports'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    group.crime_reports:
      <<: *customize
      friendly_name: Crime Reports
    
    sensor.crime_reports:
      <<: *customize
      friendly_name: Chrime Reports
      icon: mdi:radio-tower

##################################################
## Group
##################################################
group:
  crime_reports:
    control: hidden
    entities:
      - sensor.crime_reports

##################################################
## Sensor
##################################################
sensor:
  - platform: crimereports
    name: crime_reports
    radius: 16000