################################################################
## Packages / Date Time
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "date_time"

##################################################
## Sensor
##################################################
sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
