################################################################
## Packages / Emulated Hue
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'emulated_hue'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

#################################################
## Emulated Hue
#################################################
emulated_hue:
  expose_by_default: false
  exposed_domains:
    - switch