################################################################
## Packages / Google Music
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'google_music'

      expose: &expose
        <<: *customize
        haaska_hidden: false
    
    media_player.gpm_desktop_player:
      <<: *customize
      haaska_hidden: true

##################################################
## Media Player
##################################################
media_player:
  - platform: gpmdp
    host: !secret google_music_host