################################################################
## Packages / Google Calendar
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'google_calendar'

##################################################
## Google Calendar
##################################################
google:
  client_id: !secret google_calender_client_id
  client_secret: !secret google_calendar_secret