################################################################
## Packages / Google Assistant
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'google_assistant'

##################################################
## Google Assistant
##################################################
google_assistant:
  project_id: !secret ga_project_id
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  api_key: !secret ga_api_key
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - media_player
    - fan
    - scene
    - script
  entity_config:
    light.computer_floorlamp:
      expose: false
    light.tree:
      expose: false
    light.floorlamp:
      expose: false
    light.modeling_desk:
      expose: false
    light.blue_room:
      expose: false
    light.overhead:
      expose: false
    light.driveway:
      expose: false

    media_player.spotify:
      expose: false
    media_player.lg_tv_living_room:
      expose: false
    media_player.gpm_desktop_player:
      expose: false
    media_player.chris_bedroom_speaker:
      expose: false

    script.good_morning:
      expose: false
    script.chris_wakeup:
      name: Wake Up
    script.chris_bedtime:
      name: Bedtime
    script.downstairs_bedtime:
      expose: false
    script.notify_discord:
      expose: false
    script.notify_all:
      expose: false
    script.notify_voice:
      expose: false
    script.people_arriving_home:
      expose: false