################################################################
## Packages / Google Location
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'google_location'

##################################################
## Device Tracker
##################################################
device_tracker:
  - platform: google_maps
    username: admin@moosemanstudios.com
    password: Gordon24