################################################################
## Packages / Google Music
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'google_music'

      expose: &expose
        <<: *customize
        haaska_hidden: false

##################################################
## Media Player
##################################################
media_player:
  - platform: gpmdp
    host: 192.168.1.16