################################################################
## Packages / Google Assistant
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'google_assistant'

##################################################
## Google Assistant
##################################################
google_assistant:
  project_id: !secret ga_project_id
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  api_key: !secret ga_api_key
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - fan
    - scene
    - script
  entity_config:
    light.computer_floorlamp:
      expose: false
    light.tree:
      expose: false
    light.floorlamp:
      expose: false
    light.model:
      expose: false
    light.overhead_2:
      expose: false
    light.blue_room:
      expose: false
    light.living_room:
      expose: false
    light.toy_room:
      expose: false
    light.overhead_3:
      expose: false
    light.reading:
      expose: true
    light.overhead:
      expose: true
    light.garage:
      expose: true
    light.outside:
      expose: true
    light.other:
      expose: false

    script.good_morning:
      expose: false
    script.chris_wakeup:
      name: Wake Up
    script.chris_bedtime:
      name: Bedtime
    script.downstairs_bedtime:
      expose: false
    script.notify_discord:
      expose: false
    script.notify_html5:
      expose: false
    script.notify_voice:
      expose: false
    script.people_arriving_home:
      expose: false
    script.outside_lights_on:
      expose: false

    switch.scentsy:
      expose: false