################################################################
## Packages / Google Assistant
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'google_assistant'

      expose: &expose
        <<: *customize
        haaska_hidden: false

    media_player.chris_bedroom_speaker:
      <<: *customize
      google_assistant: false

##################################################
## Google Assistant
##################################################
google_assistant:
  project_id: !secret ga_project_id
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  api_key: !secret ga_api_key
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - media_player
    - fan
    - scene
    - script