################################################################
## Packages / Google Music
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'google_music'

##################################################
## Media Player
##################################################
media_player:
  - platform: gpmdp
    host: !secret google_music_host