################################################################
## Packages / Have I Been Pwned
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "haveibeenpwned"

##################################################
## Sensor
##################################################
sensor:
  platform: haveibeenpwned
  email:
    - lckyby517@aol.com
    - moose51789@gmail.com
