################################################################
## Packages / History
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'history'

      expose: &expose
        <<: *customize
        haaska_hidden: false

################################################
## History
################################################
history:
  exclude:
    entities:
      - sensor.time
      - sensor.date
    domains:
      - automation
      - group
      - updater
      - time
