################################################################
## Packages / House Mode
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "house_mode"

    input_boolean.guest_mode:
      <<: *customize
      friendly_name: "Guest Mode"
      icon: mdi:account

    sensor.household:
      <<: *customize
      friendly_name: "Household"

    sensor.house_mode:
      <<: *customize
      friendly_name: "House Mode"

    automation.notify_house_mode_changed:
      <<: *customize
      friendly_name: "Notify House Mode Changed"

    scene.mode_house:
      <<: *customize
      friendly_name: "House Mode"

    scene.mode_guest:
      <<: *customize
      friendly_name: "Guest Mode"

################################################
## Group
################################################
group:
  household_members_source:
    control: hidden
    entities:
      - device_tracker.chris_phone
      - device_tracker.teresa_phone
      - device_tracker.bruce_phone

################################################
## Input Boolean
################################################
input_boolean:
  guest_mode:
    initial: off

  vacation_mode:
    initial: off

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      household:
        entity_id: group.household_members_source
        value_template: >-
          {% if is_state('group.household_members_source', 'home') %}
            home
          {% else %}
            away
          {% endif %}
        icon_template: >-
          {% if is_state('group.household_members_source', 'home') %}
            mdi:home
          {% else %}
            mdi:home-outline
          {% endif %}

      house_mode:
        entity_id:
          - input_boolean.guest_mode
          - input_boolean.vacation_mode
          - sensor.household
        value_template: >-
          {% if is_state('input_boolean.guest_mode', 'on') %}
            guest
          {% elif is_state('sensor.household', 'home') %}
            home
          {% else %}
            away
          {% endif %}
        icon_template: >-
          {% if is_state('input_boolean.guest_mode', 'on') %}
            mdi:account
          {% elif is_state('sensor.household', 'home') %}
            mdi:home
          {% else %}
            mdi:home-outline
          {% endif %}

##################################################
## Scenes
##################################################
scene:
  - name: mode_house
    entities:
      input_boolean.guest_mode: off
      input_boolean.vacation_mode: off
  - name: mode_guest
    entities:
      input_boolean.guest_mode: on
      input_boolean.vacation_mode: off

##################################################
## Automation
##################################################
automation:
  - alias: notify_house_mode_changed
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.house_mode
    action:
      - service: script.notify_discord
        data_template:
          message: "Enabled {{ trigger.to_state.state }} Mode"
