################################################################
## Packages / HTTP
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "http"

################################################
## HTTP
################################################
http:
  api_password: !secret http_pass
  base_url: !secret http_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3
  ssl_certificate: /home/homeassistant/.homeassistant/secrets/domain-crt.crt
  ssl_key: /home/homeassistant/.homeassistant/secrets/domain-key.key
  server_port: 8123
