################################################################
## Packages / Hue
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'hue'

      expose: &expose
        <<: *customize
        haaska_hidden: false

##################################################
## Hue
##################################################
hue:
  bridges:
    - host: 10.19.136.71