################################################################
## Packages / Hue
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'hue'

##################################################
## Hue
##################################################
hue:
  bridges:
    - host: 10.19.136.122