################################################################
## Packages / LG TV
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "lg_tv"

    media_player.lg_tv:
      <<: *customize
      friendly_name: "LG Smart TV (Living Room)"
      icon: mdi:monitor

##################################################
## Media Player
##################################################
media_player:
  - platform: lg_netcast
    name: lg_tv
    host: !secret lg_tv_living_room_host
    port: 8001
    access_token: !secret lg_tv_living_room_access_token
    mac: !secret lg_tv_living_room_mac
##################################################
## Remote
##################################################
#remote:
#  - platform: lg_netcast
#    name: lg_tv_remote
#    host: !secret lg_tv_living_room_host
#    port: 8001
#    access_token: !secret lg_tv_living_room_access_token
