################################################################
## Packages / Groups / Lights
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "groups/lights"

##################################################
## Light
##################################################
light:
  - platform: group
    name: Outside
    entities:
      - light.garage
      - light.porch

  - platform: group
    name: Spare Room
    entities:
      - light.overhead_3

  - platform: group
    name: Model Room
    entities:
      - light.overhead_3
      - light.sonoff_6

  - platform: group
    name: Computer Room
    entities:
      - light.sonoff_3

  - platform: group
    name: Chris Room
    entities:
      - light.overhead
      - light.sonoff_1

  - platform: group
    name: Living Room
    entities:
      - light.sonoff_2
      - light.sonoff_4

  - platform: group
    name: Toy Room
    entities:
      - light.overhead_2

  - platform: group
    name: Downstairs
    entities:
      - light.sonoff_3
      - light.sonoff_4
      - light.sonoff_2
      - light.overhead_2

  - platform: group
    name: Upstairs
    entities:
      - light.overhead
      - light.overhead_3
      - light.sonoff_1
      - light.sonoff_6
