################################################################
## Packages / Logbook
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'logbook'

      expose: &expose
        <<: *customize
        haaska_hidden: false

################################################
## Logbook
################################################
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
    domains:
      - sun
      - time