################################################################
## Packages / Map
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'map'

      expose: &expose
        <<: *customize
        haaska_hidden: false

##################################################
## Map
##################################################
map: