################################################################
## Packages / Front End
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'frontend'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################
    group.moon:
      <<: *customize
      friendly_name: "Moon Phase"

################################################
## Group
################################################
group:
  moon:
    control: hidden
    entities:
      - sensor.moon

################################################
## Sensor
################################################
sensor:
  - platform: moon