################################################################
## Packages / MQTT
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'mqtt'

################################################
## MQTT
################################################
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: "home/hass/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "home/hass/LWT"
    payload: "Offline"
    qos: 1
    retain: true