################################################################
## Packages / Network
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'network_devices'

    automation.network_status_change:
      <<: *customize
      friendly_name: "Network Status Change"

    group.network_devices_source:
      <<: *customize
      friendly_name: "Network Devices"
      hidden: true

    group.network_devices:
      <<: *customize
      friendly_name: "Network Devices"

    group.network_switches:
      <<: *customize
      friendly_name: "Network Switches"

    group.network_cameras:
      <<: *customize
      friendly_name: "Network Cameras"

    device_tracker.net_printer_computer_room:
      <<: *customize
      friendly_name: "HP Printer (Computer Room)"
      hidden: true

    device_tracker.net_echo_show_chris_bedroom:
      <<: *customize
      friendly_name: "Echo Show (Chris)"
      hidden: true
    
    device_tracker.net_asus_tablet:
      <<: *customize
      friendly_name: "Asus Tablet (Teresa)"
      hidden: true

    device_tracker.net_asus_laptop_gaming:
      <<: *customize
      friendly_name: "Asus Gaming Laptop (Chris)"
      hidden: true

    device_tracker.net_samsung_smart_tv_chris_bedroom:
      <<: *customize
      friendly_name: "Samsung Smart TV (Chris)"
      hidden: true

    device_tracker.net_xbox_one_chris_bedroom:
      <<: *customize
      friendly_name: "Xbox One (Chris)"
      hidden: true

    device_tracker.net_lenovo_laptop:
      <<: *customize
      friendly_name: "Lenovo Laptop (Teresa)"
      hidden: true

    device_tracker.net_amazon_kindle:
      <<: *customize
      friendly_name: "Amazon Kindle (Teresa)"
      hidden: true

    device_tracker.net_amazon_firestick:
      <<: *customize
      friendly_name: "Amazon Fire Stick (Living Room)"
      hidden: true

    device_tracker.net_amazon_firestick_2:
      <<: *customize
      friendly_name: "Amazon Fire Stick (Toy Room)"
      hidden: true

    device_tracker.net_amazon_firestick_3:
      <<: *customize
      friendly_name: "Amazon Fire Stick (Master Bedroom)"
      hidden: true

    device_tracker.net_lg_smart_tv_living_room:
      <<: *customize
      friendly_name: "LG Smart TV (Living Room)"
      hidden: true

    device_tracker.net_ps3_chris_bedroom:
      <<: *customize
      friendly_name: "PlayStation 3 (Chris)"
      hidden: true

    device_tracker.net_echo_living_room:
      <<: *customize
      friendly_name: "Echo Dot (Living Room)"
      hidden: true

    device_tracker.net_sonoff_1:
      <<: *customize
      friendly_name: "Sonoff Basic #1"
      hidden: true

    device_tracker.net_sonoff_2:
      <<: *customize
      friendly_name: "Sonoff Basic #2"
      hidden: true

    device_tracker.net_sonoff_3:
      <<: *customize
      friendly_name: "Sonoff Basic #3"
      hidden: true

    device_tracker.net_sonoff_4:
      <<: *customize
      friendly_name: "Sonoff Basic #4"
      hidden: true

    device_tracker.net_sonoff_5:
      <<: *customize
      friendly_name: "Sonoff Basic #5"
      hidden: true

    device_tracker.net_sonoff_6:
      <<: *customize
      friendly_name: "Sonoff SV #1"
      hidden: true

    device_tracker.net_googlehome:
      <<: *customize
      friendly_name: "Google Home Mini"
      hidden: true

    device_tracker.net_hp_laptop:
      <<: *customize
      friendly_name: "HP Laptop"
      hidden: true

    device_tracker.net_hue_bridge:
      <<: *customize
      friendly_name: "Philips Hue Bridge"
      hidden: true

    device_tracker.net_alfred_cam_1:
      <<: *customize
      friendly_name: "Alfred Camera #1"
      hidden: true
    
    device_tracker.net_alfred_cam_2:
      <<: *customize
      friendly_name: "Alfred Camera #2"

    device_tracker.net_alfred_cam_3:
      <<: *customize
      friendly_name: "Alfred Camera #3"

    sensor.net_printer_computer_room:
      <<: *customize
      friendly_name: "HP Printer (Computer Room)"

    sensor.net_echo_show_chris_bedroom:
      <<: *customize
      friendly_name: "Echo Show (Chris)"
    
    sensor.net_asus_tablet:
      <<: *customize
      friendly_name: "Asus Tablet (Teresa)"

    sensor.net_asus_laptop_gaming:
      <<: *customize
      friendly_name: "Asus Gaming Laptop (Chris)"

    sensor.net_samsung_smart_tv_chris_bedroom:
      <<: *customize
      friendly_name: "Samsung Smart TV (Chris)"

    sensor.net_xbox_one_chris_bedroom:
      <<: *customize
      friendly_name: "Xbox One (Chris)"

    sensor.net_lenovo_laptop:
      <<: *customize
      friendly_name: "Lenovo Laptop (Teresa)"

    sensor.net_amazon_kindle:
      <<: *customize
      friendly_name: "Amazon Kindle (Teresa)"

    sensor.net_amazon_firestick:
      <<: *customize
      friendly_name: "Amazon Fire Stick (Living Room)"

    sensor.net_amazon_firestick_2:
      <<: *customize
      friendly_name: "Amazon Fire Stick (Toy Room)"

    sensor.net_amazon_firestick_3:
      <<: *customize
      friendly_name: "Amazon Fire Stick (Master Bedroom)"

    sensor.net_lg_smart_tv_living_room:
      <<: *customize
      friendly_name: "LG Smart TV (Living Room)"

    sensor.net_ps3_chris_bedroom:
      <<: *customize
      friendly_name: "PlayStation 3 (Chris)"

    sensor.net_echo_living_room:
      <<: *customize
      friendly_name: "Echo Dot (Living Room)"

    sensor.net_hp_laptop:
      <<: *customize
      friendly_name: "HP Laptop"

    sensor.net_sonoff_1:
      <<: *customize
      friendly_name: "Sonoff Basic #1"

    sensor.net_sonoff_2:
      <<: *customize
      friendly_name: "Sonoff Basic #2"
    
    sensor.net_sonoff_3:
      <<: *customize
      friendly_name: "Sonoff Basic #3"

    sensor.net_sonoff_4:
      <<: *customize
      friendly_name: "Sonoff Basic #4"

    sensor.net_sonoff_5:
      <<: *customize
      friendly_name: "Sonoff Basic #5"

    sensor.net_sonoff_6:
      <<: *customize
      friendly_name: "Sonoff SV #1"

    sensor.net_googlehome:
      <<: *customize
      friendly_name: "Google Home Mini"

    sensor.net_hue_bridge:
      <<: *customize
      friendly_name: "Philips Hue Bridge"

    sensor.net_alfred_cam_1:
      <<: *customize
      friendly_name: "Alfred Camera #1 (J7)"

    sensor.net_alfred_cam_2:
      <<: *customize
      friendly_name: "Alfred Camera #2 (S6 Edge+)"

    sensor.net_alfred_cam_3:
      <<: *customize
      friendly_name: "Alfred Camera #3 (Pixel 2)"

################################################
## Group
################################################
group:
  network_devices_source:
    control: hidden
    entities:
      - device_tracker.net_printer_computer_room
      - device_tracker.net_echo_show_chris_bedroom
      - device_tracker.net_asus_tablet
      - device_tracker.net_asus_laptop_gaming
      - device_tracker.net_samsung_smart_tv_chris_bedroom
      - device_tracker.net_xbox_one_chris_bedroom
      - device_tracker.net_lenovo_laptop
      - device_tracker.net_amazon_kindle
      - device_tracker.net_amazon_firestick
      - device_tracker.net_amazon_firestick_2
      - device_tracker.net_amazon_firestick_3
      - device_tracker.net_lg_smart_tv_living_room
      - device_tracker.net_echo_living_room
      - device_tracker.net_googlehome
      - device_tracker.net_hp_laptop
      - device_tracker.net_sonoff_1
      - device_tracker.net_sonoff_2
      - device_tracker.net_sonoff_3
      - device_tracker.net_sonoff_4
      - device_tracker.net_sonoff_5
      - device_tracker.net_sonoff_6
      - device_tracker.net_hue_bridge
      - device_tracker.net_alfred_cam_1
      - device_tracker.net_alfred_cam_2
      - device_tracker.net_alfred_cam_3

  network_devices:
    control: hidden
    entities:
      - sensor.net_printer_computer_room
      - sensor.net_echo_show_chris_bedroom
      - sensor.net_asus_tablet
      - sensor.net_asus_laptop_gaming
      - sensor.net_samsung_smart_tv_chris_bedroom
      - sensor.net_xbox_one_chris_bedroom
      - sensor.net_amazon_kindle
      - sensor.net_amazon_firestick
      - sensor.net_amazon_firestick_2
      - sensor.net_amazon_firestick_3
      - sensor.net_lenovo_laptop
      - sensor.net_lg_smart_tv_living_room
      - sensor.net_echo_living_room
      - sensor.net_googlehome
      - sensor.net_hp_laptop
      - sensor.net_hue_bridge

  network_switches:
    control: hidden
    entities:
      - sensor.net_sonoff_1
      - sensor.net_sonoff_2
      - sensor.net_sonoff_3
      - sensor.net_sonoff_4
      - sensor.net_sonoff_5
      - sensor.net_sonoff_6

  network_cameras:
    control: hidden
    entities:
      - sensor.net_alfred_cam_1
      - sensor.net_alfred_cam_2
      - sensor.net_alfred_cam_3

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      net_printer_computer_room:
        value_template: "{{ 'online' if is_state('device_tracker.net_printer_computer_room', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_printer_computer_room', 'home') else 'mdi:alert-circle' }}"

      net_echo_show_chris_bedroom:
        value_template: "{{ 'online' if is_state('device_tracker.net_echo_show_chris_bedroom', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_echo_show_chris_bedroom', 'home') else 'mdi:alert-circle' }}"

      net_asus_tablet:
        value_template: "{{ 'online' if is_state('device_tracker.net_asus_tablet', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_asus_tablet', 'home') else 'mdi:alert-circle' }}"

      net_asus_laptop_gaming:
        value_template: "{{ 'online' if is_state('device_tracker.net_asus_laptop_gaming', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_asus_laptop_gaming', 'home') else 'mdi:alert-circle' }}"
        
      net_samsung_smart_tv_chris_bedroom:
        value_template: "{{ 'online' if is_state('device_tracker.net_samsung_smart_tv_chris_bedroom', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_samsung_smart_tv_chris_bedroom', 'home') else 'mdi:alert-circle' }}"

      net_xbox_one_chris_bedroom:
        value_template: "{{ 'online' if is_state('device_tracker.net_xbox_one_chris_bedroom', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_xbox_one_chris_bedroom', 'home') else 'mdi:alert-circle' }}"

      net_lenovo_laptop:
        value_template: "{{ 'online' if is_state('device_tracker.net_lenovo_laptop', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_lenovo_laptop', 'home') else 'mdi:alert-circle' }}"

      net_amazon_kindle:
        value_template: "{{ 'online' if is_state('device_tracker.net_amazon_kindle', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_amazon_kindle', 'home') else 'mdi:alert-circle' }}"

      net_amazon_firestick:
        value_template: "{{ 'online' if is_state('device_tracker.net_amazon_firestick', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_amazon_firestick', 'home') else 'mdi:alert-circle' }}"

      net_amazon_firestick_2:
        value_template: "{{ 'online' if is_state('device_tracker.net_amazon_firestick_2', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_amazon_firestick_2', 'home') else 'mdi:alert-circle' }}"

      net_amazon_firestick_3:
        value_template: "{{ 'online' if is_state('device_tracker.net_amazon_firestick_3', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_amazon_firestick_3', 'home') else 'mdi:alert-circle' }}"

      net_lg_smart_tv_living_room:
        value_template: "{{ 'online' if is_state('device_tracker.net_lg_smart_tv_living_room', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_lg_smart_tv_living_room', 'home') else 'mdi:alert-circle' }}"

      net_echo_living_room:
        value_template: "{{ 'online' if is_state('device_tracker.net_echo_living_room', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_echo_living_room', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_1:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_1', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_1', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_2:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_2', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_2', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_3:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_3', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_3', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_4:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_4', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_4', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_5:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_5', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_5', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_6:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_6', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_6', 'home') else 'mdi:alert-circle' }}"

      net_googlehome:
        value_template: "{{ 'online' if is_state('device_tracker.net_googlehome', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_googlehome', 'home') else 'mdi:alert-circle' }}"

      net_hp_laptop:
        value_template: "{{ 'online' if is_state('device_tracker.net_hp_laptop', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_hp_laptop', 'home') else 'mdi:alert-circle' }}"

      net_hue_bridge:
        value_template: "{{ 'online' if is_state('device_tracker.net_hue_bridge', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_hue_bridge', 'home') else 'mdi:alert-circle' }}"

      net_alfred_cam_1:
        value_template: "{{ 'online' if is_state('device_tracker.net_alred_cam_1', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_alred_cam_1', 'home') else 'mdi:alert-circle' }}"

      net_alfred_cam_2:
        value_template: "{{ 'online' if is_state('device_tracker.net_alred_cam_2', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_alred_cam_2', 'home') else 'mdi:alert-circle' }}"

      net_alfred_cam_3:
        value_template: "{{ 'online' if is_state('device_tracker.net_alred_cam_3', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_alred_cam_3', 'home') else 'mdi:alert-circle' }}"

################################################
## Automation
################################################
automation:
  - alias: network_status_change
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - sensor.net_printer_computer_room
          - sensor.net_echo_show_chris_bedroom
          - sensor.net_asus_tablet
          - sensor.net_asus_laptop_gaming
          - sensor.net_samsung_smart_tv_chris_bedroom
          - sensor.net_xbox_one_chris_bedroom
          - sensor.net_lenovo_laptop
          - sensor.net_amazon_kindle
          - sensor.net_amazon_firestick
          - sensor.net_amazon_firestick_2
          - sensor.net_amazon_firestick_3
          - sensor.net_lg_smart_tv_living_room
          - sensor.net_echo_living_room
          - sensor.net_googlehome
          - sensor.net_hp_laptop
          - sensor.net_sonoff_1
          - sensor.net_sonoff_2
          - sensor.net_sonoff_3
          - sensor.net_sonoff_4
          - sensor.net_sonoff_5
          - sensor.net_sonoff_6
          - sensor.net_hue_bridge
          - sensor.net_alfred_cam_1
          - sensor.net_alfred_cam_2
          - sensor.net_alfred_cam_3
    action:
      - service: script.notify_discord
        data_template:
          message: '{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}'