################################################################
## Packages / Network
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "network_devices"

    automation.network_status_change:
      <<: *customize
      friendly_name: "Network Status Change"

    sensor.net_bedroom_esp_1:
      <<: *customize
      friendly_name: "ESP #1"

    sensor.net_hp_printer:
      <<: *customize
      friendly_name: "HP Printer (Computer Room)"

    sensor.net_echo_show:
      <<: *customize
      friendly_name: "Echo Show (Chris)"

    sensor.net_echo_dot:
      <<: *customize
      friendly_name: "Echo Dot (Teresa)"

    sensor.net_asus_tablet:
      <<: *customize
      friendly_name: "Asus Tablet (Teresa)"

    sensor.net_asus_laptop_gaming:
      <<: *customize
      friendly_name: "Asus Gaming Laptop (Chris)"

    sensor.net_samsung_smart_tv:
      <<: *customize
      friendly_name: "Samsung Smart TV (Chris)"

    sensor.net_xbox_one:
      <<: *customize
      friendly_name: "Xbox One (Chris)"

    sensor.net_xbox_one_x:
      <<: *customize
      friendly_name: "Xbox One X (Chris)"

    sensor.net_lenovo_laptop:
      <<: *customize
      friendly_name: "Lenovo Laptop (Teresa)"

    sensor.net_amazon_kindle:
      <<: *customize
      friendly_name: "Amazon Kindle (Teresa)"

    sensor.net_amazon_firestick:
      <<: *customize
      friendly_name: "Amazon Fire Stick (Living Room)"

    sensor.net_amazon_firestick_2:
      <<: *customize
      friendly_name: "Amazon Fire Stick (Toy Room)"

    sensor.net_amazon_firestick_3:
      <<: *customize
      friendly_name: "Amazon Fire Stick (Master Bedroom)"

    sensor.net_lg_smart_tv:
      <<: *customize
      friendly_name: "LG Smart TV (Living Room)"

    sensor.net_ps3:
      <<: *customize
      friendly_name: "PlayStation 3 (Chris)"

    sensor.net_hp_laptop:
      <<: *customize
      friendly_name: "HP Laptop"

    sensor.net_sonoff_1:
      <<: *customize
      friendly_name: "Sonoff Basic #1"

    sensor.net_sonoff_2:
      <<: *customize
      friendly_name: "Sonoff Basic #2"

    sensor.net_sonoff_3:
      <<: *customize
      friendly_name: "Sonoff Basic #3"

    sensor.net_sonoff_4:
      <<: *customize
      friendly_name: "Sonoff Basic #4"

    sensor.net_sonoff_5:
      <<: *customize
      friendly_name: "Sonoff Basic #5"

    sensor.net_sonoff_6:
      <<: *customize
      friendly_name: "Sonoff SV #1"

    sensor.net_google_home:
      <<: *customize
      friendly_name: "Google Home Mini"

    sensor.net_google_home_2:
      <<: *customize
      friendly_name: "Google Home Mini #2"

    sensor.net_google_home_3:
      <<: *customize
      friendly_name: "Google Home Mini #3"

    sensor.net_chromecast_audio:
      <<: *customize
      friendly_name: "Chromecast Audio #1"

    sensor.net_chromecast_audio_2:
      <<: *customize
      friendly_name: "Chromecast Audio #2"

    sensor.net_google_home_hub:
      <<: *customize
      friendly_name: "Google Home Hub"

    sensor.net_hue_bridge:
      <<: *customize
      friendly_name: "Philips Hue Bridge"

    sensor.net_alfred_cam_1:
      <<: *customize
      friendly_name: "Alfred Camera #1 (J7)"

    sensor.net_alfred_cam_2:
      <<: *customize
      friendly_name: "Alfred Camera #2 (S6 Edge+)"

    sensor.net_alfred_cam_3:
      <<: *customize
      friendly_name: "Alfred Camera #3 (Pixel 2)"

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      net_hp_printer:
        value_template: "{{ 'online' if is_state('device_tracker.net_hp_printer', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_hp_printer', 'home') else 'mdi:alert-circle' }}"

      net_bedroom_esp_1:
        value_template: "{{ 'online' if is_state('device_tracker.net_bedroom_esp_1', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_bedroom_esp_1', 'home') else 'mdi:alert-circle' }}"

      net_echo_show:
        value_template: "{{ 'online' if is_state('device_tracker.net_echo_show', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_echo_show', 'home') else 'mdi:alert-circle' }}"

      net_echo_dot:
        value_template: "{{ 'online' if is_state('device_tracker.net_echo_dot', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_echo_dot', 'home') else 'mdi:alert-circle' }}"

      net_asus_tablet:
        value_template: "{{ 'online' if is_state('device_tracker.net_asus_tablet', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_asus_tablet', 'home') else 'mdi:alert-circle' }}"

      net_asus_laptop_gaming:
        value_template: "{{ 'online' if is_state('device_tracker.net_asus_laptop_gaming', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_asus_laptop_gaming', 'home') else 'mdi:alert-circle' }}"

      net_samsung_smart_tv:
        value_template: "{{ 'online' if is_state('device_tracker.net_samsung_smart_tv', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_samsung_smart_tv', 'home') else 'mdi:alert-circle' }}"

      net_xbox_one:
        value_template: "{{ 'online' if is_state('device_tracker.net_xbox_one', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_xbox_one', 'home') else 'mdi:alert-circle' }}"

      net_xbox_one_x:
        value_template: "{{ 'online' if is_state('device_tracker.net_xbox_one_x', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_xbox_one_x', 'home') else 'mdi:alert-circle' }}"

      net_lenovo_laptop:
        value_template: "{{ 'online' if is_state('device_tracker.net_lenovo_laptop', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_lenovo_laptop', 'home') else 'mdi:alert-circle' }}"

      net_amazon_kindle:
        value_template: "{{ 'online' if is_state('device_tracker.net_amazon_kindle', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_amazon_kindle', 'home') else 'mdi:alert-circle' }}"

      net_amazon_firestick:
        value_template: "{{ 'online' if is_state('device_tracker.net_amazon_firestick', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_amazon_firestick', 'home') else 'mdi:alert-circle' }}"

      net_amazon_firestick_2:
        value_template: "{{ 'online' if is_state('device_tracker.net_amazon_firestick_2', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_amazon_firestick_2', 'home') else 'mdi:alert-circle' }}"

      net_amazon_firestick_3:
        value_template: "{{ 'online' if is_state('device_tracker.net_amazon_firestick_3', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_amazon_firestick_3', 'home') else 'mdi:alert-circle' }}"

      net_lg_smart_tv:
        value_template: "{{ 'online' if is_state('device_tracker.net_lg_smart_tv', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_lg_smart_tv', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_1:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_1', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_1', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_2:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_2', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_2', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_3:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_3', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_3', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_4:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_4', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_4', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_5:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_5', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_5', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_6:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_6', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_6', 'home') else 'mdi:alert-circle' }}"

      net_google_home:
        value_template: "{{ 'online' if is_state('device_tracker.net_google_home', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_google_home', 'home') else 'mdi:alert-circle' }}"

      net_google_home_2:
        value_template: "{{ 'online' if is_state('device_tracker.net_google_home_2', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_google_home_2', 'home') else 'mdi:alert-circle' }}"

      net_google_home_3:
        value_template: "{{ 'online' if is_state('device_tracker.net_google_home_3', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_google_home_3', 'home') else 'mdi:alert-circle' }}"

      net_chromecast_audio:
        value_template: "{{ 'online' if is_state('device_tracker.net_chromecast_audio', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_chromecast_audio', 'home') else 'mdi:alert-circle' }}"

      net_chromecast_audio_2:
        value_template: "{{ 'online' if is_state('device_tracker.net_chromecast_audio_2', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_chromecast_audio_2', 'home') else 'mdi:alert-circle' }}"

      net_google_home_hub:
        value_template: "{{ 'online' if is_state('device_tracker.net_google_home_hub', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_google_home_hub', 'home') else 'mdi:alert-circle' }}"

      net_hp_laptop:
        value_template: "{{ 'online' if is_state('device_tracker.net_hp_laptop', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_hp_laptop', 'home') else 'mdi:alert-circle' }}"

      net_hue_bridge:
        value_template: "{{ 'online' if is_state('device_tracker.net_hue_bridge', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_hue_bridge', 'home') else 'mdi:alert-circle' }}"

      net_alfred_cam_1:
        value_template: "{{ 'online' if is_state('device_tracker.net_alfred_cam_1', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_alfred_cam_1', 'home') else 'mdi:alert-circle' }}"

      net_alfred_cam_2:
        value_template: "{{ 'online' if is_state('device_tracker.net_alfred_cam_2', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_alfred_cam_2', 'home') else 'mdi:alert-circle' }}"

      net_alfred_cam_3:
        value_template: "{{ 'online' if is_state('device_tracker.net_alfred_cam_3', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_alfred_cam_3', 'home') else 'mdi:alert-circle' }}"

################################################
## Automation
################################################
automation:
  - alias: network_status_change
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - sensor.net_bedroom_esp_1
          - sensor.net_echo_show
          - sensor.net_echo_dot
          - sensor.net_amazon_firestick
          - sensor.net_amazon_firestick_2
          - sensor.net_amazon_firestick_3
          - sensor.net_google_home
          - sensor.net_google_home_2
          - sensor.net_google_home_3
          - sensor.net_google_home_hub
          - sensor.net_chromecast_audio
          - sensor.net_chromecast_audio_2
          - sensor.net_sonoff_1
          - sensor.net_sonoff_2
          - sensor.net_sonoff_3
          - sensor.net_sonoff_4
          - sensor.net_sonoff_5
          - sensor.net_sonoff_6
          - sensor.net_hue_bridge
          - sensor.net_alfred_cam_1
          - sensor.net_alfred_cam_2
          - sensor.net_alfred_cam_3
    action:
      - service: script.notify_discord
        data_template:
          message: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}"
      - service: script.notify_voice_chris
        data_template:
          message: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}"
