################################################################
## Packages / Views
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'network_devices'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.network_devices_source:
      <<: *customize
      friendly_name: "Network Devices"
      hidden: true

    group.network_devices:
      <<: *customize
      friendly_name: "Network Devices"

    ################################################
    ## Device Tracker
    ################################################

    device_tracker.net_printer_computer_room:
      <<: *customize
      friendly_name: "HP Printer (Computer Room)"
      hidden: true

    device_tracker.net_echo_show_chris_bedroom:
      <<: *customize
      friendly_name: "Echo Show (Chris)"
      hidden: true
    
    device_tracker.net_asus_tablet:
      <<: *customize
      friendly_name: "Asus Tablet (Teresa)"
      hidden: true

    device_tracker.net_asus_laptop_gaming:
      <<: *customize
      friendly_name: "Asus Gaming Laptop (Chris)"
      hidden: true

    device_tracker.net_samsung_smart_tv_chris_bedroom:
      <<: *customize
      friendly_name: "Samsung Smart TV (Chris)"
      hidden: true

    device_tracker.net_xbox_one_chris_bedroom:
      <<: *customize
      friendly_name: "Xbox One (Chris)"
      hidden: true

    device_tracker.net_lenovo_laptop:
      <<: *customize
      friendly_name: "Lenovo Laptop (Teresa)"
      hidden: true
    
    device_tracker.net_lg_smart_tv_living_room:
      <<: *customize
      friendly_name: "LG Smart TV (Living Room)"
      hidden: true

    device_tracker.net_ps3_chris_bedroom:
      <<: *customize
      friendly_name: "PlayStation 3 (Chris)"
      hidden: true

    device_tracker.net_echo_living_room:
      <<: *customize
      friendly_name: "Echo Dot (Living Room)"
      hidden: true

    device_tracker.net_sonoff_chris_bedroom:
      <<: *customize
      friendly_name: "Sonoff Basic (Chris)"
      hidden: true

    device_tracker.net_sonoff_chris_bedroom_2:
      <<: *customize
      friendly_name: "Sonoff Basic #2 (Chris)"
      hidden: true

    ################################################
    ## Sensor
    ################################################

    sensor.net_printer_computer_room:
      <<: *customize
      friendly_name: "HP Printer (Computer Room)"

    sensor.net_echo_show_chris_bedroom:
      <<: *customize
      friendly_name: "Echo Show (Chris)"
    
    sensor.net_asus_tablet:
      <<: *customize
      friendly_name: "Asus Tablet (Teresa)"

    sensor.net_asus_laptop_gaming:
      <<: *customize
      friendly_name: "Asus Gaming Laptop (Chris)"

    sensor.net_samsung_smart_tv_chris_bedroom:
      <<: *customize
      friendly_name: "Samsung Smart TV (Chris)"

    sensor.net_xbox_one_chris_bedroom:
      <<: *customize
      friendly_name: "Xbox One (Chris)"

    sensor.net_lenovo_laptop:
      <<: *customize
      friendly_name: "Lenovo Laptop (Teresa)"
    
    sensor.net_lg_smart_tv_living_room:
      <<: *customize
      friendly_name: "LG Smart TV (Living Room)"

    sensor.net_ps3_chris_bedroom:
      <<: *customize
      friendly_name: "PlayStation 3 (Chris)"

    sensor.net_echo_living_room:
      <<: *customize
      friendly_name: "Echo Dot (Living Room)"

    sensor.net_sonoff_chris_bedroom:
      <<: *customize
      friendly_name: "Sonoff Basic (Chris Room)"

    sensor.net_sonoff_chris_bedroom_2:
      <<: *customize
      friendly_name: "Sonoff Basic #2 (Chris Room)"

################################################
## Group
################################################

group:
  network_devices_source:
    control: hidden
    entities:
      - device_tracker.net_printer_computer_room
      - device_tracker.net_echo_show_chris_bedroom
      - device_tracker.net_asus_tablet
      - device_tracker.net_asus_laptop_gaming
      - device_tracker.net_samsung_smart_tv_chris_bedroom
      - device_tracker.net_xbox_one_chris_bedroom
      - device_tracker.net_lenovo_laptop
      - device_tracker.net_lg_smart_tv_living_room
      - device_tracker.net_echo_living_room
      - device_tracker.net_sonoff_chris_bedroom
      - device_tracker.net_sonoff_chris_bedroom_2

  network_devices:
    control: hidden
    entities:
      - sensor.net_printer_computer_room
      - sensor.net_echo_show_chris_bedroom
      - sensor.net_asus_tablet
      - sensor.net_asus_laptop_gaming
      - sensor.net_samsung_smart_tv_chris_bedroom
      - sensor.net_xbox_one_chris_bedroom
      - sensor.net_lenovo_laptop
      - sensor.net_lg_smart_tv_living_room
      - sensor.net_echo_living_room
      - sensor.net_sonoff_chris_bedroom
      - sensor.net_sonoff_chris_bedroom_2

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      net_printer_computer_room:
        value_template: "{{ 'online' if is_state('device_tracker.net_printer_computer_room', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_printer_computer_room', 'home') else 'mdi:alert-circle' }}"

      net_echo_show_chris_bedroom:
        value_template: "{{ 'online' if is_state('device_tracker.net_echo_show_chris_bedroom', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_echo_show_chris_bedroom', 'home') else 'mdi:alert-circle' }}"

      net_asus_tablet:
        value_template: "{{ 'online' if is_state('device_tracker.net_asus_tablet', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_asus_tablet', 'home') else 'mdi:alert-circle' }}"

      net_asus_laptop_gaming:
        value_template: "{{ 'online' if is_state('device_tracker.net_asus_laptop_gaming', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_asus_laptop_gaming', 'home') else 'mdi:alert-circle' }}"
        
      net_samsung_smart_tv_chris_bedroom:
        value_template: "{{ 'online' if is_state('device_tracker.net_samsung_smart_tv_chris_bedroom', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_samsung_smart_tv_chris_bedroom', 'home') else 'mdi:alert-circle' }}"

      net_xbox_one_chris_bedroom:
        value_template: "{{ 'online' if is_state('device_tracker.net_xbox_one_chris_bedroom', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_xbox_one_chris_bedroom', 'home') else 'mdi:alert-circle' }}"

      net_lenovo_laptop:
        value_template: "{{ 'online' if is_state('device_tracker.net_lenovo_laptop', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_lenovo_laptop', 'home') else 'mdi:alert-circle' }}"

      net_lg_smart_tv_living_room:
        value_template: "{{ 'online' if is_state('device_tracker.net_lg_smart_tv_living_room', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_lg_smart_tv_living_room', 'home') else 'mdi:alert-circle' }}"

      net_echo_living_room:
        value_template: "{{ 'online' if is_state('device_tracker.net_echo_living_room', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_echo_living_room', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_chris_bedroom:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_chris_bedroom', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_chris_bedroom', 'home') else 'mdi:alert-circle' }}"

      net_sonoff_chris_bedroom_2:
        value_template: "{{ 'online' if is_state('device_tracker.net_sonoff_chris_bedroom_2', 'home') else 'offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.net_sonoff_chris_bedroom_2', 'home') else 'mdi:alert-circle' }}"

################################################
## Automation
################################################

automation:
  - alias: network_status_change
    hide_entity: true
    trigger:
      - platform: state
        entity_id:
          - sensor.net_printer_computer_room
          - sensor.net_echo_show_chris_bedroom
          - sensor.net_asus_tablet
          - sensor.net_asus_laptop_gaming
          - sensor.net_samsung_smart_tv_chris_bedroom
          - sensor.net_xbox_one_chris_bedroom
          - sensor.net_lenovo_laptop
          - sensor.net_lg_smart_tv_living_room
          - sensor.net_echo_living_room
          - sensor.net_sonoff_chris_bedroom
          - sensor.net_sonoff_chris_bedroom_2
        to: 'offline'
        for:
          minutes: 5
    action:
      - service: notify.discord
        data_template:
          target: '355096664241078272'
          message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] {{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}'