################################################################
## Packages / Notify
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'notify'

    script.notify_discord:
      <<: *customize
      friendly_name: Notify Discord

    script.notify_all:
      <<: *customize
      friendly_name: Notify All

    script.notify_voice:
      <<: *customize
      friendly_name: Notify Voice

##################################################
## Notify
##################################################
notify:
  - platform: discord
    name: discord
    token: !secret discord_token
  - name: notifications
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

##################################################
## Script
##################################################
script:
  notify_discord:
    sequence:
      - service: notify.discord
        data_template:
          target: '355096664241078272'
          message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] {{ message }}'
  notify_all:
    sequence:
      - service: notify.notifications
        data_template:
          message: '{{ message }}'
          data:
            tag: '{{ tag }}'

  # google home TTS
  notify_voice:
    sequence:
      - condition: state
        entity_id: device_tracker.chris_phone
        state: 'home'
      - condition: state
        entity_id: input_boolean.chris_bed
        state: 'off'
      - service: media_player.volume_set
        data:
          entity_id: media_player.chris_bedroom_speaker
          volume_level: 0.4
      - service: tts.google_say
        data_template:
          cache: false
          message: '{{ message }}'            
          entity_id: media_player.chris_bedroom_speaker