################################################################
## Packages / Notify
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'notify'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    script.notify_discord:
      <<: *customize
      friendly_name: Notify Discord
      haaska_hidden: true

    script.notify_all:
      <<: *customize
      friendly_name: Notify All
      haaska_hidden: true

##################################################
## Notify
##################################################
notify:
  - platform: discord
    name: discord
    token: !secret discord_token
  - name: notifications
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

##################################################
## Script
##################################################
script:
  notify_discord:
    sequence:
      - service: notify.discord
        data_template:
          target: '355096664241078272'
          message: '[{{ as_timestamp(now()) | timestamp_custom("%H:%M:%S") }}] {{ message }}'
  notify_all:
    sequence:
      - service: notify.notifications
        data_template:
          message: '{{ message }}'
          data:
            tag: '{{ tag }}'