################################################################
## Packages / OwnTracks
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'owntracks'

      expose: &expose
        <<: *customize
        haaska_hidden: false

################################################
## Device Trackers
################################################
device_tracker:
  - platform: owntracks_http
    max_gps_accuracy: 200
    waypoints: True
    waypoints_whitelist:
      - chris_miller
      - teresa_dills