################################################################
## Packages / Pihole
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'pihole'

    group.pihole:
      <<: *customize
      friendly_name: PiHole

##################################################
## Sensor
##################################################
sensor:
  - platform: pi_hole
    host: !secret pihole_host

##################################################
## Group
##################################################
group:
  pihole:
    control: hidden
    entities:
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_qeries_cached
      - sensor.pihole_dns_queries_forwarded
      - sensor.pihole_dns_queries_today
      - sensor.pihole_dns_unique_clients
      - sensor.pihole_dns_unique_domains
      - sensor.pihole_domains_blocked