################################################################
## Packages / Plex
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "plex"

##################################################
## Media Player
##################################################
media_player:
  - platform: plex
    entity_namespace: 'plex'
    scan_interval: 5
    remove_unavailable_clients: false

##################################################
## Sensor
##################################################
sensor:
  - platform: template
    sensors:
      plex_list:
        value_template: >-
          {%- if states.sensor.plex.attributes -%}
            {% set space = joiner(' ') %}
            {%- for attr in states.sensor.plex.attributes -%}
             {%- if not attr=="friendly_name" and not attr=="unit_of_measurement" -%}
              {{space()}}{{attr}} is watching {{states.sensor.plex.attributes[attr]}}.
             {%- endif -%}
            {%- endfor -%}
          {%- else -%}
            No Current Activity
          {%- endif -%}
