################################################################
## Packages / Plex
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'plex'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

##################################################
## Media Player
##################################################
media_player:
  - platform: plex