################################################################
## Packages / Reading Time
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'reading_time'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
    
    group.reading_time:
      <<: *customize
      friendly_name: Reading Time

    input_number.reading_time_volume:
      <<: *customize
      friendly_name: Spotify Volume
      icon: mdi:volume-high

    input_select.reading_time_playlist:
      <<: *customize
      friendly_name: Spotify Playlist
      icon: mdi:spotify

    input_select.reading_time_source:
      <<: *customize
      friendly_name: Source
      icon: mdi:speaker-wireless

    script.reading_time:
      <<: *customize
      friendly_name: Reading Time
      haaska_name: Reading Time
      icon: mdi:play
    
    script.reading_time_off:
      <<: *customize
      friendly_name: Done Reading
      icon: mdi:stop

##################################################
## Group
##################################################
group:
  reading_time:
    control: hidden
    entities:
      - input_select.reading_time_playlist
      - input_select.reading_time_source
      - input_number.reading_time_volume
      - script.reading_time

##################################################
## Input Number
##################################################
input_number:
  reading_time_volume:
    initial: 0.4
    min: 0
    max: 1
    step: 0.05

##################################################
## Input Select
##################################################
input_select:
  reading_time_playlist:
    options:
      - 'Classical' 
      #|'
      - 'Christmas' 
      #|'
  
  reading_time_source:
    options:
      - Google Home 
      - Chris Laptop
      - Echo Show 

##################################################
## Script
##################################################
script:
  # Turn on
  reading_time:
    sequence:
      - service: light.turn_on
        data: 
          entity_id: light.reading_light
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.spotify
          volume_level: '{{ states.input_number.reading_time_volume.state }}'
      - service: media_player.select_source
        data_template:
          entity_id: media_player.spotify
          source: >-
            {% if is_state('input_select.reading_time_source', 'Google Home') %}Chris Bedroom Speaker
            {% elif is_state('input_select.reading_time_source', 'Chris Laptop') %}CHRISMILLERPC
            {% elif is_state('input_select.reading_time_source', 'Echo Show') %}Christopher's Echo Show
            {% endif %}
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify
          media_content_type: playlist
          media_content_id: >-
            {% if is_state('input_select.reading_time_playlist', 'Classical') %}spotify:user:spotify:playlist:37i9dQZF1DX4sWSpwq3LiO
            {% elif is_state('input_select.reading_time_playlist', 'Christmas') %}spotify:user:spotify:playlist:37i9dQZF1DX6R7QUWePReA
            {% endif %}

  # Turn Off
  reading_time_off:
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.reading_light
      - service: media_player.media_pause
        data:
          entity_id: media_player.spotify

##################################################
## Automation
##################################################
automation:
  # Volume changed in dashboard
  - alias: reading_time_volume_changed
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_number.reading_time_volume
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.spotify
          volume_level: '{{ states.input_number.reading_time_volume.state }}'

  # Playlist changed
  - alias: reading_time_source_changed
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.reading_time_source
    action:
      - service: media_player.select_source
        data_template:
          entity_id: media_player.spotify
          source: >-
            {% if is_state('input_select.reading_time_source', 'Google Home') %}Chris Bedroom Speaker
            {% elif is_state('input_select.reading_time_source', 'Chris Laptop') %}CHRISMILLERPC
            {% elif is_state('input_select.reading_time_source', 'Echo Show') %}Christopher's Echo Show
            {% endif %}

  - alias: reading_time_playlist_changed
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.reading_time_playlist
    action:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify
          media_content_type: playlist
          media_content_id: >-
            {% if is_state('input_select.reading_time_playlist', 'Classical') %}spotify:user:spotify:playlist:37i9dQZF1DX4sWSpwq3LiO
            {% elif is_state('input_select.reading_time_playlist', 'Christmas') %}spotify:user:spotify:playlist:37i9dQZF1DX6R7QUWePReA
            {% endif %} 