################################################################
## Packages / Reading Time
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "reading_time"

    automation.reading_time_playlist_changed:
      <<: *customize
      friendly_name: Reading Time Playlist Changed

    automation.reading_time_source_changed:
      <<: *customize
      friendly_name: Reading Time Source Changed

    automation.reading_time_volume_changed:
      <<: *customize
      friendly_name: Reading Time Volume Changed

    input_boolean.reading_time:
      <<: *customize
      friendly_name: Reading Time
      icon: mdi:book

    input_number.reading_time_volume:
      <<: *customize
      friendly_name: Spotify Volume
      icon: mdi:volume-high

    input_select.reading_time_playlist:
      <<: *customize
      friendly_name: Spotify Playlist
      icon: mdi:spotify

    input_select.reading_time_source:
      <<: *customize
      friendly_name: Source
      icon: mdi:speaker-wireless

##################################################
## Input Boolean
##################################################
input_boolean:
  reading_time:

##################################################
## Input Number
##################################################
input_number:
  reading_time_volume:
    initial: 0.4
    min: 0
    max: 1
    step: 0.05

##################################################
## Input Select
##################################################
input_select:
  reading_time_playlist:
    options:
      - "Classical"
      - "Christmas"

  reading_time_source:
    options:
      - Google Home
      - Chris Laptop
      - Echo Show

##################################################
## Automation
##################################################
automation:
  # Volume changed in dashboard
  - alias: reading_time_volume_changed
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_number.reading_time_volume
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.spotify
          volume_level: "{{ states.input_number.reading_time_volume.state }}"

  # Source changed
  - alias: reading_time_source_changed
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.reading_time_source
    action:
      - service: media_player.select_source
        data_template:
          entity_id: media_player.spotify
          source: >-
            {% if is_state('input_select.reading_time_source', 'Chris Laptop') %}CHRISMILLERPC
            {% elif is_state('input_select.reading_time_source', 'Echo Show') %}Christopher's Echo Show
            {% endif %}

  # Playlist Changed
  - alias: reading_time_playlist_changed
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.reading_time_playlist
    action:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.spotify
          media_content_type: playlist
          media_content_id: >-
            {% if is_state('input_select.reading_time_playlist', 'Classical') %}spotify:user:spotify:playlist:37i9dQZF1DX4sWSpwq3LiO
            {% elif is_state('input_select.reading_time_playlist', 'Christmas') %}spotify:user:spotify:playlist:37i9dQZF1DX6R7QUWePReA
            {% endif %}