################################################################
## Packages / Recorder
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'recorder'

################################################
## Recorder
################################################
recorder:
  purge_interval: 2
  purge_keep_days: 14