################################################################
## Packages / Recorder
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'recorder'

      expose: &expose
        <<: *customize
        haaska_hidden: false

################################################
## Recorder
################################################
recorder:
  purge_interval: 2
  purge_keep_days: 14