################################################################
## Packages / Speedtest
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "speedtest"

    binary_sensor.internet_ping:
      <<: *customize
      friendly_name: Internet Pingable

################################################
## Speed Test
################################################
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

##################################################
## Binary Sensor
##################################################
binary_sensor:
  - platform: ping
    host: 1.1.1.1
    name: internet_ping
    scan_interval: 30
