################################################################
## Packages / Spotify
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'spotify'

      expose: &expose
        <<: *customize
        haaska_hidden: false

    media_player.spotify:
      <<: *customize
      google_assistant_type: media_player

##################################################
## Media Player
##################################################
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret