################################################################
## Packages / Steam Online
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'steam_online'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    group.steam:
      <<: *customize
      friendly_name: "Steam"

    sensor.steam_76561197993303163:
      <<: *customize
      friendly_name: "Moose517"

################################################
## Group
################################################
group:
  steam:
    control: hidden
    entities:
      - sensor.steam_76561197993303163

################################################
## Sensor
################################################
sensor:
  - platform: steam_online
    api_key: !secret steam_api_key
    accounts:
      - !secret steam_user_id