################################################################
## Packages / system
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "system"

################################################
## Sensor
################################################
sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      - type: network_in
        arg: "Wi-Fi"
      - type: network_out
        arg: "Wi-Fi"
      - type: processor_use
