################################################################
## Packages / Temperature & Humidity
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'temp_humidity'

    group.environment:
      <<: *customize
      friendly_name: Current Environment

################################################
## Group
################################################
group:
  environment:
    control: hidden
    entities:
      - sensor.temperature
      - sensor.humidity

################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    name: "Temperature"
    state_topic: "/ESP_Easy/Environment/Temperature"
    unit_of_measurement: "°F"
  
  - platform: mqtt
    name: "Humidity"
    state_topic: "/ESP_Easy/Environment/Humidity"
    unit_of_measurement: "%"
