################################################################
## Packages / TTS
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'tts'

      expose: &expose
        <<: *customize
        haaska_hidden: false

################################################
## TTS
################################################
tts:
  - platform: google