################################################################
## Packages / Twitch
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'twitch'

    group.twitch:
      <<: *customize
      friendly_name: "Twitch Streams"

    automation.notify_twitch_user_online:
      <<: *customize
      friendly_name: Twitch User Goes Online

##################################################
## Group
##################################################
group:
  twitch:
    control: hidden
    entities:
      - sensor.moose517
      - sensor.juhstinfx
      - sensor.khanjal

##################################################
## Sensor
##################################################
sensor:
  platform: twitch
  client_id: !secret twitch_client_id
  channels:
    - moose517
    - juhstinfx
    - khanjal

##################################################
## Automation
##################################################
automation:
  - alias: notify_twitch_user_online
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - sensor.moose517
          - sensor.juhstinfx
          - sensor.khanjal
        from: 'offline'
    action:
      - service: script.notify_discord
        data_template:
          message: '{{ trigger.to_state.attributes.friendly_name }} has started streaming.'
      - service: script.notify_voice
        data_template:
          message: '{{ trigger.to_state.attributes.friendly_name }} has started streaming on twich.'

