################################################################
## Packages / Unifi
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'unifi'

      expose: &expose
        <<: *customize
        haaska_hidden: false

################################################
## Device Trackers
################################################
device_tracker:
  - platform: unifi_direct
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    track_new_devices: true
    interval_seconds: 1
    consider_home: 10