################################################################
## Packages / UPS
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'ups'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.ups_packages:
      <<: *expose
      friendly_name: "UPS Packages"

    ################################################
    ## Sensor
    ################################################

    sensor.ups:
      <<: *customize
      friendly_name: "UPS packages"
      icon: mdi:package-variant-closed
      unit-measurement: 'packages'


################################################
## Group
################################################

group:
  ups_packages:
    control: hidden
    entities:
      - sensor.ups

################################################
## Sensor
################################################
sensor:
  - platform: ups
    username: !secret ups_username
    password: !secret ups_password