################################################################
## Packages / Uptime
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'uptime'

    group.uptime:
      <<: *customize
      friendly_name: Server Uptime

##################################################
## Group
##################################################
group:
  uptime:
    control: hidden
    entities:
      - sensor.uptime

##################################################
## Sensor
##################################################
sensor:
  - platform: uptime
    unit_of_measurement: hours