################################################################
## Packages / Uptime
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "uptime"

    automation.website_status_change:
      <<: *customize
      friendly_name: Website Service Status Change

################################################
## Automation
################################################
automation:
  - alias: website_status_change
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.clm_me
          - binary_sensor.clm_me_api
          - binary_sensor.clm_me_invoicing
          - binary_sensor.hscresteds_com
          - binary_sensor.miller_house
          - binary_sensor.moosecraft_us_app
    action:
      - service: script.notify_discord
        data_template:
          message: "Website {{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}line"
      - service: script.notify_html5
        data_template:
          message: "website {{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}line"
      - service: script.notify_voice_chris
        data_template:
          message: "Website {{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}line"

##################################################
## Sensor
##################################################
sensor:
  - platform: uptime
    unit_of_measurement: hours

##################################################
## Binary Sensor
##################################################
binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptime_robot_key
