################################################################
## Packages / Uptime
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "uptime"

##################################################
## Sensor
##################################################
sensor:
  - platform: uptime
    unit_of_measurement: hours

##################################################
## Binary Sensor
##################################################
binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptime_robot_key
