################################################################
## Packages / Uptime
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "uptime"

##################################################
## Sensor
##################################################
sensor:
  - platform: uptime
    unit_of_measurement: hours
