################################################################
## Packages / Views
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'views'

      expose: &expose
        <<: *customize
        haaska_hidden: false

    group.automation:
      <<: *customize
      friendly_name: "Automation"
      icon: mdi:settings

    group.default_view:
      <<: *customize
      friendly_name: "Home"
      icon: mdi:home

    group.network:
      <<: *customize
      friendly_name: "Network"
      icon: mdi:switch

    group.media:
      <<: *customize
      friendly_name: "Media"
      icon: mdi:play-circle-outline

    group.weather:
      <<: *customize
      friendly_name: "Weather"
      icon: mdi:weather-partlycloudy

    group.misc:
      <<: *customize
      friendly_name: "Misc."
      icon: mdi:puzzle

    group.gaming:
      <<: *customize
      friendly_name: "Gaming"
      icon: mdi:gamepad-variant

################################################
## Group
################################################
group:
  default_view:
    view: yes
    entities:
      - group.alarm_control_panel
      - group.house_mode
      - group.household_members
      - group.guests
      - group.batteries
      - group.mail_packages
      - group.crime_reports
  
  network:
    view: yes
    entities:
      - group.network_devices
      - group.speedtest
      - group.utilities
      - group.uptime

  automation:
    view: yes
    entities:
      - group.all_automations
      - group.all_scripts
      - group.all_scenes


  media:
    view: yes
    entities:
      - group.media_components
      - group.media_players

  weather:
    view: yes
    entities:
      - group.weather_general
      - group.weather_radar
      - group.weather_darksky
      - group.weather_wunderground
      - group.airvisual

  misc:
    view: yes
    entities:
      - group.iss
      - group.bitcoin_general
      - group.haveibeenpwned
      - group.aircraft_overhead

  gaming:
    view: yes
    entities:
      - group.minecraft_servers
      - group.xbox_live
      - group.steam
      - group.twitch