################################################################
## Packages / Voice Notifications
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: "voice_notifications"

    input_boolean.voice_enabled:
      <<: *customize
      friendly_name: Voice Notifications

    input_boolean.voice_enabled_chris:
      <<: *customize
      friendly_name: Voice Notifications Chris

##################################################
## Input Number
##################################################
input_number:
  voice_volume:
    initial: 0.5
    min: 0
    max: 1
    step: 0.01

##################################################
## Input Boolean
##################################################
input_boolean:
  voice_enabled:
    initial: on
    icon: mdi:voice
  voice_enabled_chris:
    initial: on
    icon: mdi:voice
