################################################################
## Packages / Windy
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'windy'

##################################################
## Panel
##################################################
panel_iframe:
  windy:
    title: 'Windy'
    url: !secret windy_url
    icon: mdi:weather-windy