################################################################
## Packages / Workday
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'workday'

      expose: &expose
        <<: *customize
        haaska_hidden: false

##################################################
## Binary Sensor
##################################################
binary_sensor:
  - platform: workday
    country: US