################################################################
## Packages / Xbox Live
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'xbox_live'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    group.xbox_live:
      <<: *customize
      friendly_name: "Xbox Live"

    sensor.lckyby517:
      <<: *customize
      friendly_name: "LckyBy517"

    sensor.xbox_current_activity:
      <<: *customize
      friendly_name:  "Current Activity"

################################################
## Group
################################################
group:
  xbox_live:
    control: hidden
    entities:
      - sensor.lckyby517
      - sensor.xbox_current_activity

################################################
## Sensor
################################################
sensor:
  - platform: xbox_live
    api_key: !secret xbox_live_api_key
    xuid:
      - !secret xbox_live_xuid

  - platform: template
    sensors:
      xbox_current_activity:
        value_template: >-
          {%- if is_state('sensor.lckyby517', 'Online') -%}
            {{ states.sensor.lckyby517.attributes['XboxOne Full'] }}
          {%- else -%}
            Offline
          {%- endif -%}
        icon_template: >-
          {%- if is_state('sensor.lckyby517', 'Online') -%}
            mdi:{{ states.sensor.lckyby517.attributes['XboxOne Full'].lower() }}
          {%- else -%}
            mdi:xbox-controller-off
          {%- endif -%}