################################################################
## Packages / Xbox Live
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'xbox_live'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Sensor
    ################################################

    sensor.lckyby517:
      <<: *customize
      friendly_name: "LckyBy517"

################################################
## Sensor
################################################

sensor:
  - platform: xbox_live
    api_key: !secret xbox_live_api_key
    xuid:
      - !secret xbox_live_xuid