################################################################
## Packages / Zones
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'zones'

      expose: &expose
        <<: *customize
        haaska_hidden: false

    zone.home:
      <<: *customize
      friendly_name: "Home"
      icon: mdi:home

    zone.masterbrand:
      <<: *customize
      friendly_name: "Masterbrand LLC"
      icon: mdi:worker

    zone.cass_bill:
      <<: *customize
      friendly_name: "Cass & Bills"
      icon: mdi:account

################################################
## Zone
################################################

zone:
  - name: home
    latitude: !secret zone_home_lat
    longitude: !secret zone_home_long
    radius: 150

  - name: masterbrand
    latitude: !secret zone_masterbrand_lat
    longitude: !secret zone_masterbrand_long
    radius: 300

  - name: cass_bill
    latitude: !secret zone_cassie_bill_lat
    longitude: !secret zone_cassie_bill_long
    radius: 150